/*!
 * hAzzle.js
 * Copyright (c) 2014 Kenny Flashlight
 * Version: 1.0.0 Release Candidate
 * Released under the MIT License.
 *
 * Date: 2014-10-24
 */
(function(){var c=/^#([\w\-]*)$/,k={},f={},q=function(d,c,a){if(d)throw d=Error("[hAzzle-"+c+"] "+a),d.code=c,d;},l=function(d){return d&&(d.ELEMENT_NODE||d.DOCUMENT_NODE)},m=function(d,k){if(d){if(!(this instanceof m))return new m(d,k);if(d instanceof m)return d;var a;a=m.require("Util");var b=m.require("Ready");"function"===typeof d&&(f.Ready?b.ready(d):q(!0,6,"ready.js module not installed"));if("string"===typeof d){if((a=c.exec(d))&&!k&&(this.elements=[document.getElementById(a[1])]),null===this.elements||
void 0===this.elements)this.elements=this.find(d,k,!0)}else d instanceof Array?this.elements=a.unique(a.filter(d,l)):this.isNodeList(d)?this.elements=a.filter(a.makeArray(d),l):this.elements=d.nodeType?11===d.nodeType?d.children:[d]:d===window?[d]:[];void 0===this.elements?(this.length=0,this.elements=[]):this.length=this.elements.length;return this}};m.prototype={constructor:m};m.version="1.0.0a-rc";m.err=q;m.installed=f;m.require=function(d){return k[d]};m.define=function(d,c){q("string"!==typeof d,
1,'id must be a string "'+d+'"');q(k[d],2,'id already defined "'+d+'"');q("function"!==typeof c,3,'function body for "'+d+'" must be an function "'+c+'"');f[d]=!0;k[d]=c.call(m.prototype)};window.hAzzle=m})(window);var hAzzle=window.hAzzle||(window.hAzzle={});
hAzzle.define("Support",function(){var c,k,f,q,l=function(a){var b=document.createElement("fieldset");try{return!!a(b)}catch(d){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}},m,d;f=document.createElement("input");m=document.createElement("select").appendChild(document.createElement("option"));f.type="checkbox";m=m.selected;f=document.createElement("input");f.value="t";f.type="radio";d="t"===f.value;var t;t="function"===typeof document.implementation.createHTMLDocument?!0:!1;l(function(a){a.classList.add("a",
"b");c=!!document.documentElement.classList;k=/(^| )a( |$)/.test(a.className)&&/(^| )b( |$)/.test(a.className)});f=l(function(a){return a.compareDocumentPosition(document.createElement("div"))&1});l(function(a){a=document.createDocumentFragment().appendChild(a);var b=document.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);a.innerHTML="<textarea>x</textarea>";q=!!a.cloneNode(!0).lastChild.defaultValue});return{assert:l,
optSelected:m,radioValue:d,imcHTML:t,classList:c,multipleArgs:k,sortDetached:f,noCloneChecked:q,cS:!!document.defaultView.getComputedStyle}});
hAzzle.define("has",function(){var c=navigator.userAgent,k=window,f="undefined"!==typeof window&&"undefined"!==typeof location&&"undefined"!==typeof document&&window.location===location&&window.document===document&&document,q=f&&f.createElement("div"),l={};ie=function(){if(f.documentMode)return f.documentMode;for(var c=7;4<c;c--){var d=f.createElement("div");d.innerHTML="\x3c!--[if IE "+c+"]><span></span><![endif]--\x3e";if(d.getElementsByTagName("span").length)return c}}();has=function(c){return"function"===
typeof l[c]?l[c]=l[c](k,f,q):l[c]};add=function(c,d,f,a){("undefined"===typeof l[c]||a)&&(l[c]=d);return f&&has(c)};clearElement=function(c){if(c)for(;c.lastChild;)c.removeChild(c.lastChild);return c};add("xpath",function(){return!!f.evaluate});add("air",function(){return!!k.runtime});add("dart",function(){return!(!k.startDart&&!f.startDart)});add("promise",function(){return!!k.Promise});add("mobile",function(){return/^Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(c)});add("android",
function(){return/^Android/i.test(c)});add("opera",function(){return!!k.opera||0<=c.indexOf(" OPR/")});add("firefox",function(){return"undefined"!==typeof InstallTrigger});add("chrome",function(){return k.chrome});add("webkit",function(){return"WebkitAppearance"in f.documentElement.style});add("safari",function(){return 0<Object.prototype.toString.call(k.HTMLElement).indexOf("Constructor")});add("ie",function(){return!!f.documentMode});add("touch",function(){return"ontouchstart"in document||"onpointerdown"in
document&&0<navigator.maxTouchPoints||window.navigator.msMaxTouchPoints});add("touchEvents",function(){return"ontouchstart"in document});add("pointerEvents",function(){return"onpointerdown"in document});add("MSPointer",function(){return"msMaxTouchPoints"in navigator});return{has:has,add:add,clearElement:clearElement,ie:ie}});
hAzzle.define("Types",function(){var c,k=Object.prototype.toString,f=Array.isArray,q={},l="Arguments Array Boolean Date Error Function Map Number Object RegExp Set StringWeakMap ArrayBuffer Float32Array Float64Array Int8Array Int16Array Int32ArrayUint8Array Uint8ClampedArray Uint16Array Uint32Array".split(" ");for(c=l.length;c--;)q["[object "+l[c]+"]"]=!0;l="ArrayBuffer Float32Array Float64Array Int8Array Int16Array Int32Array Uint8Array Uint8ClampedArray Uint16Array Uint32Array".split(" ");for(c=
l.length;c--;)q["[object "+l[c]+"]"]=!1;var m=function(b){return"number"===typeof b},d=function(b){return b&&b.window===b},t=function(b){return b?function(a){return k.call(a)==="[object "+b+"]"}:function(){}},a=function(b){var a=typeof b;return"function"===a||b&&"object"===a||!1};this.isNodeList=c=function(b){var a=Object.prototype.toString.call(b);if("[object HTMLCollection]"===a||"[object NodeList]"===a)return!0;if(!("length"in b&&"item"in b))return!1;try{if(null===b(0)||b(0)&&b(0).tagName)return!0}catch(c){}return!1};
return{isType:t,isFunction:t("Function"),isArray:f,isEmpty:function(b){if(b instanceof hAzzle&&0<b.length)return!1;var c=0;if(f(b))b=0===b.length;else if(a(b)){for(var d in b){c++;break}b=0===c}else b=""===b;return b},isWindow:d,isObject:a,isPlainObject:function(b){return"object"!==t(b)&&!d(b)&&Object.getPrototypeOf(b)==Object.prototype},isEmptyObject:function(b){for(var a in b)return!1;return!0},isNode:function(b){return!!b&&"object"===typeof b&&"nodeType"in b},isElement:function(b){return b&&"object"===
typeof b&&b.ELEMENT_NODE&&-1<k.call(b).indexOf("Element")||!1},isString:function(b){return"string"===typeof b},isArrayLike:function(b){return b&&"object"===typeof b&&"number"===typeof b.length&&q[k.call(b)]||!1},isNumber:m,isBoolean:function(b){return"boolean"===typeof b},isNumeric:function(b){return!f(b)&&0<=b-parseFloat(b)+1},isNaN:function(b){return m(b)&&b!=+b},isDefined:function(b){return"undefined"!==typeof b},isUndefined:function(b){return"undefined"===typeof b},isNodeList:c,isHostMethod:function(b,
a){var c=typeof b[a];return"function"===c||!("object"!=c||!b[a])||"unknown"==c}}});hAzzle.define("Text",function(){var c=function(k){if(k){var f,q="",l=0,m=k.length;f=k.nodeType;if(!f)for(;l<m;l++)f=k[l++],8!==f.nodeType&&(q+=c(f));else if(1===f||9===f||11===f){l=k.textContent;if("string"===typeof l)return k.textContent;for(k=k.firstChild;k;k=k.nextSibling)q+=c(k)}else if(3===f||4===f)return k.nodeValue;return q}};return{getText:c}});
hAzzle.define("Util",function(){var c=hAzzle.require("Types"),k=Object.prototype.hasOwnProperty,f=Array.prototype.slice,q=Object.keys,l=function(e,h){return k.call(e,h)},m=function(e,h,b,v){if(void 0===e)return e;"function"!==typeof h&&hAzzle.err(!0,5,"'fn' must be a function in util.each()");h=d(h,b);var a;b=e.length;if(b===+b)for(a=0;a<b&&(a=v?e.length-a-1:a,!1!==h(e[a],a,e));a++);else if(e)for(a in e)if(!1===h(e[a],a,e))break;return e},d=function(e,h,b){if("function"===typeof e){if(void 0===h)return e;
b=b?b:3;return 1===b?function(b){return e.call(h,b)}:2===b?function(b,a){return e.call(h,b,a)}:3===b?function(b,a,c){return e.call(h,b,a,c)}:4===b?function(b,a,c,s){return e.call(h,b,a,c,s)}:function(){return e.apply(h,arguments)}}if(!e)return a},t=function(e,h,x){return e?c.isFunction(e)?d(e,h,x):c.isObject(e)?b(e):u(e):a},a=function(e){return e},b=function(e){var h=p(e),b=h.length;return function(e){if(!e)return!b;e=Object(e);for(var a=0,c,s;a<b;a++)if(c=h[a],s=c[0],c[1]!==e[s]||!(s in e))return!1;
return!0}},p=function(e){for(var h=q(e),b=h.length,a=Array(b),c=0;c<b;c++)a[c]=[h[c],e[h[c]]];return a},u=function(e){return function(h){return h[e]}},g=function(e,h,b){if(null==e)return-1;var a=0,c=e.length;if(b)if("number"===typeof b)a=0>b?Math.max(0,c+b):b;else return a=r(e,h),e[a]===h?a:-1;for(;a<c;a++)if(e[a]===h)return a;return-1},r=function(e,h,b,a){b=t(b,a,1);h=b(h);a=0;for(var c=e.length;a<c;){var d=a+c>>>1;b(e[d])<h?a=d+1:c=d}return a},n=function(e,h,b){for(var a in h)b&&(c.isPlainObject(h[a])||
c.isArray(h[a]))?(c.isPlainObject(h[a])&&!c.isPlainObject(e[a])&&(e[a]={}),c.isArray(h[a])&&!c.isArray(e[a])&&(e[a]=[]),n(e[a],h[a],b)):void 0!==h[a]&&(e[a]=h[a])};return{each:m,mixin:function(e){if(!c.isObject(e))return e;for(var a,b,d=1,g=arguments.length;d<g;d++)for(b in a=arguments[d],a)l(a,b)&&(e[b]=a[b]);return e},makeArray:function(e){if(e instanceof Array)return e;for(var a=-1,b=e.length,c=Array(b);++a<b;)c[a]=e[a];return c},merge:function(e,a){for(var b=+a.length,c=0,d=e.length;c<b;c++)e[d++]=
a[c];e.length=d;return e},acceptData:function(e){return 1===e.nodeType||9===e.nodeType||!+e.nodeType},createCallback:d,isElement:function(e){return e&&(1===e.nodeType||9===e.nodeType)},nodeName:function(e,a){return e&&e.nodeName&&e.nodeName.toLowerCase()===a.toLowerCase()},unique:function(e,a,b,d){if(!e)return[];c.isBoolean(a)&&(d=b,b=a,a=!1);void 0!==b&&(b=t(b,d));d=[];for(var r=[],f=0,s=e.length;f<s;f++){var n=e[f];if(a)f&&r===n||d.push(n),r=n;else if(b){var p=b(n,f,e);0>g(r,p)&&(r.push(p),d.push(n))}else 0>
g(d,n)&&d.push(n)}return d},sortedIndex:r,indexOf:g,property:u,matches:b,pairs:p,filter:function(e,a,b){var c=[];if(!e)return c;a=t(a,b);m(e,function(e,b,d){a(e,b,d)&&c.push(e)});return c},map:function(e,a,b){if(e){a=t(a,b);b=e.length!==+e.length&&q(e);for(var c=(b||e).length,d=Array(c),g,s=0;s<c;s++)g=b?b[s]:s,d[s]=a(e[g],g,e);return d}return[]},some:function(e,a,b){if(!e)return!1;a=t(a,b);var c=e.length!==+e.length&&c(e);b=(c||e).length;var d,g;for(d=0;d<b;d++)if(g=c?c[d]:d,a(e[g],g,e))return!0;
return!1},now:Date.now,bind:function(e,a){var b=2<arguments.length?f.call(arguments,2):[],c;"string"===typeof a&&(c=e[a],a=e,e=c);return"function"!==typeof e||a instanceof RegExp?a:b.length?function(){return arguments.length?e.apply(a||this,b.concat(f.call(arguments,0))):e.apply(a||this,b)}:function(){return arguments.length?e.apply(a||this,arguments):e.call(a||this)}},has:l,noop:function(){},extend:n,reject:function(a,b,c){for(var d=[],g=0,r=0,s=a.length;g<s;g++)g in a&&!b.call(c,a[g],g,a)&&(d[r++]=
a[g]);return d},consoleLog:function(a){"undefined"!==typeof console&&c.isHostMethod(console,"log")&&console.log(a)}}});
hAzzle.define("Core",function(){var c=window.document,k=c.documentElement,f=hAzzle.require("Support"),q=Array.prototype.indexOf,l=/^[^{]+\{\s*\[native \w/,m,d={},t={},a,b,p=function(b,c){b===c&&(a=!0);return 0},u=function(a,b){var c=b&&a,e=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(e)return e;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1};d.uidX=1;d.uidK="hAzzle_id";d.expando="hAzzle-"+String(Math.random()).replace(/\D/g,"");d.isXML=
function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};d.xmlID=function(a){var b=a.getAttribute(this.uidK);b||(b=this.uidX++,a.setAttribute(this.uidK,b));return b};d.htmlID=function(a){return a.uniqueNumber||(a.uniqueNumber=this.uidX++)};d["native"]=l.test(k.compareDocumentPosition);d.setDocument=function(g){var r=g.nodeType,n=g?g.ownerDocument||g:c;if(9!==r)if(r)n=g.ownerDocument;else if(g.navigator)n=g.document;else return;if(this.document!==n){this.document=g=n;var r=
g.documentElement,e=this.xmlID(r),h=t[e],x;if(!h){h=t[e]={};h.root=r;h.isXMLDocument=this.isXML(g);h.detectDuplicates=!!a;h.sortStable=d.expando.split("").sort(p).join("")===d.expando;f.assert(function(a){a.innerHTML='<a id="hAzzle_id"></a>';h.isHTMLDocument=!!g.getElementById("hAzzle_id")});if(!d.isXML(r)){h.getElementsByTagName=f.assert(function(a){a.appendChild(n.createComment(""));return!a.getElementsByTagName("*").length});h.getById=f.assert(function(a){a.innerHTML='<a name="hAzzle_id"></a><b id="hAzzle_id"></b>';
return g.getElementById("hAzzle_id")===a.firstChild});var r=d.rbuggyMatches=[],v=d.rbuggyQSA=[];(f.qsa=l.test(n.querySelectorAll))&&f.assert(function(a){a.innerHTML="<select msallowcapture=''><option selected=''></option></select>";a.querySelectorAll(":checked").length||v.push(":checked")});(h.matchesSelector=l.test(m=k.matches||k.webkitMatchesSelector||k.mozMatchesSelector||k.oMatchesSelector||k.msMatchesSelector))&&f.assert(function(a){d.disconnectedMatch=m.call(a,"div")});v=v.length&&new RegExp(v.join("|"));
r=r.length&&new RegExp(r.join("|"))}h.contains=d["native"]||d["native"].test(k.contains)?function(a,b){var e=9===a.nodeType?a.documentElement:a,c=b&&b.parentNode;return a===c||!!(c&&1===c.nodeType&&(e.contains?e.contains(c):a.compareDocumentPosition&&a.compareDocumentPosition(c)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};d.sortOrder=d["native"]?function(e,h){if(e===h)return a=!0,0;var s=!e.compareDocumentPosition-!h.compareDocumentPosition;if(s)return s;s=(e.ownerDocument||
e)===(h.ownerDocument||h)?e.compareDocumentPosition(h):1;return s&1||!f.sortDetached&&h.compareDocumentPosition(e)===s?e===n||e.ownerDocument===c&&d.contains(c,e)?-1:h===n||h.ownerDocument===c&&d.contains(c,h)?1:b?q.call(b,e)-q.call(b,h):0:s&4?-1:1}:function(e,h){if(e===h)return a=!0,0;var d,g=0;d=e.parentNode;var f=h.parentNode,r=[e],p=[h];if(!d||!f)return e===n?-1:h===n?1:d?-1:f?1:b?q.call(b,e)-q.call(b,h):0;if(d===f)return u(e,h);for(d=e;d=d.parentNode;)r.unshift(d);for(d=h;d=d.parentNode;)p.unshift(d);
for(;r[g]===p[g];)g++;return g?u(r[g],p[g]):r[g]===c?-1:p[g]===c?1:0};r=null}for(x in h)this[x]=h[x]}};p=d.sortOrder;d.setDocument(c);return{root:d.root,isXML:d.isXML,isHTML:!d.isXML(c),expando:d.expando,uniqueSort:function(c){var f,n=[],e=0,h=0;a=!d.detectDuplicates;b=!d.sortStable&&c.slice(0);c.sort(p);if(a){for(;f=c[h++];)f===c[h]&&(e=n.push(h));for(;e--;)c.splice(n[e],1)}b=null;return c},contains:d.contains,rbuggyQSA:d.rbuggyQSA}});
hAzzle.define("Collection",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Types"),f=Array.prototype,q=Object.keys,l=f.concat,m=f.push,d=function(a,b,d,f){a||(a=[]);b=c.createCallback(b,f,4);var g=a.length!==+a.length&&q(a),r=(g||a).length,n=0,e;3>arguments.length&&(r||hAzzle.err(!0,7," no collection length exist in collection.reduce()"),d=a[g?g[n++]:n++]);for(;n<r;n++)e=g?g[n]:n,d=b(d,a[e],e,a);return d},t=function(a,b,c){"undefined"===typeof b&&(b=0);"undefined"===typeof c&&(c=a?a.length:
0);var d=-1;c=c-b||0;for(var g=Array(0>c?0:c);++d<c;)g[d]=a[b+d];return g};this.get=function(a){return void 0===a?t(this.elements,0):0>a?this.elements[this.length+a]:this.elements[a]};this.eq=function(a){return-1===a?hAzzle(t(this.elements,this.length-1)):hAzzle(t(this.elements,a,a+1))};this.reduce=function(a,b,c){return d(this.elements,a,b,c)};this.indexOf=function(a,b,c){return null==b?-1:f.indexOf.call(b,a,c)};this.map=function(a,b){return hAzzle(c.map(this.elements,a,b))};this.each=function(a,
b,d){c.each(this.elements,a,b,d);return this};this.slice=function(a,b){return new hAzzle(t(this.elements,a,b))};this.concat=function(){var a=c.map(t(arguments),function(a){return a instanceof hAzzle?a.elements:a});return hAzzle(l.apply(this.elements,a))};this.is=function(a){return 0<this.length&&0<this.filter(a).length};this.not=function(a){return this.filter(a,!0)};this.index=function(a){var b=this.elements;return a?"string"===typeof a?c.indexOf(hAzzle(a).elements,b[0]):c.indexOf(b,a instanceof hAzzle?
a.elements[0]:a):b[0]&&b[0].parentElement?this.first().prevAll().length:-1};this.add=function(a,b){var c=a;"string"===typeof a&&(c=hAzzle(a,b).elements);return this.concat(c)};this.first=function(a){return a?this.slice(0,a):this.eq(0)};this.last=function(a){return a?this.slice(this.length-a):this.eq(-1)};this.size=function(){return this.length};c.each({next:"nextElementSibling",prev:"previousElementSibling"},function(a,b){this[b]=function(b){return this.map(function(b){return b[a]}).filter(b)}}.bind(this));
c.each({prevAll:"previousElementSibling",nextAll:"nextElementSibling"},function(a,b){this[b]=function(){var b=[];this.each(function(c){for(;(c=c[a])&&9!==c.nodeType;)b.push(c)});return hAzzle(b)}}.bind(this));return{makeArray:function(a,b){var d=b||[];void 0!==a&&(k.isArrayLike(Object(a))?c.merge(d,k.isString(a)?[a]:a):m.call(d,a));return d},slice:t,reduce:d,inArray:function(a,b,c){return void 0===b?-1:f.indexOf.call(b,a,c)}}});
hAzzle.define("Jiesa",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Core"),f=hAzzle.require("Collection"),q=hAzzle.require("Support"),l=/^\s*[+~]/,m=/[\n\t\r]/g,d=/^(?:#([\w-]+)|\.([\w-]+)|(\w+))$/,t=/^(\w+)(?:#([\w-]+)|)(?:\.([\w-]+)|)$/,a=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g,b=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),p=window.document.documentElement,u=p.matches||p.webkitMatchesSelector||p.mozMatchesSelector||p.oMatchesSelector||p.msMatchesSelector,
g=function(b,e,c){var d=b,g=b.getAttribute("id"),s=g||"__hAzzle__",f=b.parentNode,r=l.test(e);if(r&&!f)return[];g?s=s.replace(/'/g,"\\$&"):b.setAttribute("id",s);r&&f&&(b=b.parentNode);e=e.match(a);for(f=0;f<e.length;f++)e[f]="[id='"+s+"'] "+e[f];e=e.join(",");try{return c.call(b,e)}finally{g||d.removeAttribute("id")}},r=function(a,b,e){return e&&9!==e.nodeType?g(e,b,function(b){return u(a,b)}):u.call(a,b)},n=function(a,b){var e,r,u,s=[];b=b||document;if(!a||"string"!==typeof a)return s;if(1!==(r=
b.nodeType)&&9!==r&&11!==r)return[];if(-1!==c.indexOf(a,",")&&(e=a.split(",")))return c.each(e,function(a){c.each(n(a),function(a){k.contains(s,a)||s.push(a)})}),s;if(k.isHTML)if(e=d.exec(a))if(a=e[1])if(9===r)if((u=b.getElementById(a))&&u.parentNode){if(u.id===a)return[u]}else return[];else{if(b.ownerDocument&&(u=b.ownerDocument.getElementById(a))&&k.contains(b,u)&&u.id===e)return[u]}else{if(a=e[2])return f.slice(b.getElementsByClassName(a));if(a=e[3])return f.slice(b.getElementsByTagName(a))}else{if(e=
t.exec(a)){r=b.getElementsByTagName(e[1]);var l=e[2],p=e[3];c.each(r,function(a){var b;(b=a.id===l)||(b=q.classList?a.classList.contains(p):0<=(" "+a.className+" ").replace(m," ").indexOf(p));b&&s.push(a)});return s}if(q.qsa&&!k.rbuggyQSA.length)return 1===b.nodeType&&"object"!==b.nodeName.toLowerCase()?f.slice(g(b,a,b.querySelectorAll)):f.slice(b.querySelectorAll(a))}},e=function(a,d){if(d.nodeType)return a===d;(a.ownerDocument||a)!==document&&k.setDocument(a);d="string"===typeof d?d.replace(b,"='$1']"):
d;if(d instanceof hAzzle)return c.some(d.elements,function(b){return e(a,b)});if(a===document)return!1;if(k&&k.isHTML)try{var f=r(a,d);if(f||k.disconnectedMatch||a.document&&11!==a.document.nodeType)return f}catch(g){}};this.find=function(a,b,e){if(e)return n(a,b);if("string"===typeof a)return 1===this.length?hAzzle(n(a,this.elements[0])):f.reduce(this.elements,function(b,e){return hAzzle(b.concat(f.slice(n(a,e))))},[]);var d,g=this.length,s=this.elements;return hAzzle(c.filter(hAzzle(a).elements,
function(a){for(d=0;d<g;d++)if(k.contains(s[d],a))return!0}))};this.filter=function(a,b){if(void 0===a)return this;if("function"===typeof a){var e=[];this.each(function(b,c){a.call(b,c)&&e.push(b)});return hAzzle(e)}return this.filter(function(){return r(this,a)!=(b||!1)})};return{matchesSelector:r,matches:e,find:n}});
hAzzle.define("Strings",function(){var c=String.prototype.trim,k=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,f=/[A-Z]/g,q=/\b[a-z]/g,l=/^#x([\da-fA-F]+)$/,m=/^#(\d+)$/,d=/[&<>"']/g,t=/^\s*$/,a=/<\/?[^>]+>/g,b=/([.*+?^=!:${}()|[\]\/\\])/g,p=/^-ms-/,u=/-([\da-z])/gi,g=/[A-Z]/g,r=/[a-z]/g,n=[],e={lt:"<",gt:">",quot:'"',apos:"'",amp:"&"},h={},x=function(a){return a.toUpperCase()},v=function(a,b){return b.toUpperCase()},D=function(a){return"-"+a.charAt(0).toLowerCase()},w;for(w in e)h[e[w]]=w;h["'"]="#39";return{capitalize:function(a){return a?
a.replace(q,x):a},hyphenate:function(a){return"string"===typeof a?a?a.replace(f,D):a:(a="number"===typeof a?""+a:"")?"data-"+a.toLowerCase():a},camelize:function(a){return a&&"string"===typeof a?n[a]?n[a]:n[a]=a.replace(p,"ms-").replace(u,v):"number"===typeof a||"boolean"===typeof a?""+a:a},trim:function(a){return null==a?"":c?"string"===typeof a?a.trim():a:(a+"").replace(k,"")},lowercase:function(a){return"string"===typeof a?a.toLowerCase():a},uppcase:function(a){return"string"===typeof a?a.toUpperCase():
a},manualLowercase:function(a){return"string"===typeof a?a.replace(g,function(a){return String.fromCharCode(a.charCodeAt(0)|32)}):a},manualUppercase:function(a){return"string"===typeof a?a.replace(r,function(a){return String.fromCharCode(a.charCodeAt(0)&-33)}):a},parse:function(a){var b;return"string"===typeof a&&a?"false"===a?!1:"true"===a?!0:"null"===a?null:"undefined"===a||(b=+a)||0===b||"NaN"===a?b:a:a},count:function(a,b){for(var e=0,c=a.indexOf(b);0<=c;)e+=1,c=a.indexOf(b,c+1);return e},contains:function(a,
b){return 0<=a.indexOf(b)},isBlank:function(a){a||(a="");return t.test(a)},stripTags:function(b){return b?String(b).replace(a,""):""},escapeHTML:function(a){return a.replace(d,function(a){return"&"+h[a]+";"})},unescapeHTML:function(a){return a.replace(/\&([^;]+);/g,function(a,b){var c;return b in e?e[b]:(c=b.match(l))?String.fromCharCode(parseInt(c[1],16)):(c=b.match(m))?String.fromCharCode(~~c[1]):a})},escapeRegExp:function(a){return null==!a?"":String(a).replace(b,"\\$1")},truncate:function(a,b,
e){if(!a)return"";a=String(a);e=e||"...";b=~~b;return a.length>b?a.slice(0,b)+e:a}}});
hAzzle.define("Storage",function(){function c(){this.expando=m.expando+Math.random()}function k(a,b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace(t,"-$1").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:d.test(c)?JSON.parse(c+""):c}catch(f){}p.set(a,b,c)}else c=void 0;return c}var f=hAzzle.require("Util"),q=hAzzle.require("Strings"),l=hAzzle.require("Types"),m=hAzzle.require("Core"),d=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,
t=/([A-Z])/g,a=/\S+/g;c.accepts=f.acceptData;c.prototype={register:function(a,b){var c={};c[this.expando]={value:b||{},writable:!0,configurable:!0};a.nodeType?a[this.expando]={value:b||{}}:Object.defineProperties(a,c);return a[this.expando]},cache:function(a,b){if(!c.accepts(a))return{};var d=a[this.expando];return d?d:this.register(a,b)},set:function(a,b,c){if(a){var d;a=this.cache(a);if("string"===typeof b)a[b]=c;else if(l.isEmptyObject(a))f.mixin(a,b);else for(d in b)a[d]=b[d];return a}},access:function(a,
b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return c=this.get(a,b),void 0!==c?c:this.get(a,q.camelize(b));this.set(a,b,c);return void 0!==c?c:b},get:function(a,b){var c=this.cache(a);return void 0!==c&&void 0===b?c:c[b]},release:function(b,c){var d,f,e=this.cache(b);if(void 0===c)this.register(b);else for(l.isArray(c)?f=c.concat(c.map(q.camelize)):(d=q.camelize(c),c in e?f=[c,d]:(f=d,f=e[f]?[f]:f.match(a)||[])),d=f.length;d--;)delete e[f[d]]},hasData:function(a){return!l.isEmptyObject(a[this.expando]||
{})},flush:function(a){a[this.expando]&&delete a[this.expando]}};var b=new c,p=new c;this.data=function(a,c){var d,f,e,h=this.elements[0],m=h&&h.attributes;if(void 0===a){if(this.length&&(e=p.get(h),1===h.nodeType&&!b.get(h,"hasDataAttrs"))){for(d=m.length;d--;)m[d]&&(f=m[d].name,0===f.indexOf("data-")&&(f=q.camelize(f.slice(5)),k(h,f,e[f])));b.set(h,"hasDataAttrs",!0)}return e}if("object"===typeof a)return this.each(function(b){p.set(b,a)});var l=q.camelize(a);if(h&&void 0===c){e=p.get(h,a);if(void 0!==
e)return e;e=p.get(h,l);var t=b.get(this,"hasDataAttrs"),w=-1!==a.indexOf("-");if(void 0!==e)return e;e=k(h,l,void 0);if(void 0!==e)return e}else this.each(function(b){var e=p.get(b,l);p.set(b,l,c);w&&void 0!==e&&p.set(b,a,c);w&&void 0===t&&p.set(b,a,c)})};this.removeData=function(a){return this.each(function(b){p.release(b,a)})};return{"private":b,data:p}});
hAzzle.define("curCSS",function(){var c=hAzzle.require("has"),k=hAzzle.require("Core"),f=hAzzle.require("Types"),q=hAzzle.require("Util"),l=hAzzle.require("Support"),m=hAzzle.require("Storage"),d=/^(b|big|i|small|tt|abbr|acronym|cite|code|dfn|em|kbd|strong|samp|var|a|bdo|br|img|map|object|q|script|span|sub|sup|button|input|label|select|textarea)$/i,t=/^(li)$/i,a=/^(tr)$/i,b=window.document.documentElement,p=!!document.defaultView.getComputedStyle,u=l.computedStyle&&c.has("webkit")?function(a){var b;
if(1===a.nodeType){var c=a.ownerDocument.defaultView;b=c.getComputedStyle(a,null);!b&&a.style&&(a.style.display="",b=c.getComputedStyle(a,null))}return b||{}}:function(a){var b=!1;return a&&a!==window?(void 0!==a.ownerDocument&&(b=a.ownerDocument.defaultView),l.cS?b&&p?b.opener?b.getComputedStyle(a,null):window.getComputedStyle(a,null):a.style:a.style):null},g=function(a){if(a)return void 0===m["private"].get(a,"computed")&&m["private"].access(a,"computed",{computedStyle:null}),m["private"].get(a,
"computed")},r=function(a){return null===g(a).computedStyle?g(a).computedStyle=u(a):g(a).computedStyle},n=function(a,b,d){"object"===typeof a&&a instanceof hAzzle&&(a=a.elements[0]);var f=0,f=!1;"height"!==b&&"width"!==b||0!==n(a,"display")||(f=!0,a.style.display=hAzzle.getDisplayType(a));if(!d){if("height"===b&&"border-box"!==n(a,"boxSizing").toString().toLowerCase())return b=f,f=a.offsetHeight-(parseFloat(n(a,"borderTopWidth"))||0)-(parseFloat(n(a,"borderBottomWidth"))||0)-(parseFloat(n(a,"paddingTop"))||
0)-(parseFloat(n(a,"paddingBottom"))||0),b&&(a.style.display="none"),f;if("width"===b&&"border-box"!==n(a,"boxSizing").toString().toLowerCase())return b=f,f=a.offsetWidth-(parseFloat(n(a,"borderLeftWidth"))||0)-(parseFloat(n(a,"borderRightWidth"))||0)-(parseFloat(n(a,"paddingLeft"))||0)-(parseFloat(n(a,"paddingRight"))||0),b&&(a.style.display="none"),f}if(f=r(a)){(c.ie||c.has("firefox"))&&"borderColor"===b&&(b="borderTopColor");f=9===c.ie&&"filter"===b?f.getPropertyValue(b):f[b];if(""===f||null===
f)f=a.style[b];"auto"!==f||"top"!==b&&"right"!==b&&"bottom"!==b&&"left"!==b||(d=n(a,"position"),"fixed"!==d&&("absolute"!==d||"left"!==b&&"top"!==b))||(f=hAzzle(a).position()[b]+"px");return f}};this.offset=function(a){if(arguments.length)return void 0===a?this.elements:this.each(function(b,c){var d=a,h,g,k,m=n(b,"position"),C=hAzzle(b),l={};"static"===m&&(b.style.position="relative");k=C.offset();g=n(b,"top");h=n(b,"left");("absolute"===m||"fixed"===m)&&-1<(g+h).indexOf("auto")?(h=C.position(),g=
h.top,h=h.left):(g=parseFloat(g)||0,h=parseFloat(h)||0);f.isType("function")(d)&&(d=d.call(b,c,k));null!=d.top&&(l.top=d.top-k.top+g);null!=d.left&&(l.left=d.left-k.left+h);"using"in d?d.using.call(b,l):C.css(l)});var b,c;c=this.elements[0];var d={top:0,left:0},g=c&&c.ownerDocument;if(g){b=g.documentElement;if(!k.contains(b,c))return d;c.getBoundingClientRect&&(d=c.getBoundingClientRect());c=f.isWindow(g)?g:9===g.nodeType&&g.defaultView;return{top:d.top+c.pageYOffset-b.clientTop,left:d.left+c.pageXOffset-
b.clientLeft}}};this.position=function(){if(this.elements[0]){var a,b,c=this.elements[0],d={top:0,left:0};"fixed"===n(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),q.nodeName(a.elements[0],"html")||(d=a.offset()),d.top+=parseFloat(n(a.elements[0],"borderTopWidth",!0)),d.left+=parseFloat(n(a.elements[0],"borderLeftWidth",!0)));d.top-=a.scrollTop();d.left-=a.scrollLeft();return{top:b.top-d.top-parseFloat(n(c,"marginTop",!0)),left:b.left-d.left-parseFloat(n(c,"marginLeft",
!0))}}};this.offsetParent=function(){return this.map(function(){for(var a=this.offsetParent||b;a&&!q.nodeName(a,"html")&&"static"===n(a,"position");)a=a.offsetParent;return a||b})};return{computedCSS:g,getStyles:r,curCSS:n,getDisplayType:function(b){b=b.tagName.toLowerCase();return d.test(b)?"inline":t.test(b)?"list-item":a.test(b)?"table-row":"block"}}});
hAzzle.define("Units",function(){var c=hAzzle.require("curCSS"),k=hAzzle.require("Support"),f=/^(left$|right$|margin|padding)/,q=/^(relative|absolute|fixed)$/,l=/^(top|bottom)$/,m=function(d,t,a,b){if(""===t||"px"===t)return d;if("%"===t){f.test(b)?b="width":l.test(b)&&(b="height");if(a=q.test(c.curCSS(a,"position"))?a.offsetParent:a.parentNode)if(b=parseFloat(c.curCSS(a,b)),0!==b)return d/b*100;return 0}if("em"===t)return d/parseFloat(c.curCSS(a,"fontSize"));if(void 0===m.unity){var p=m.unity={};
k.assert(function(a){a.style.width="100cm";document.body.appendChild(a);p.mm=a.offsetWidth/1E3});p.cm=10*p.mm;p["in"]=2.54*p.cm;p.pt=1*p["in"]/72;p.pc=12*p.pt}return(t=m.unity[t])?d/t:d};return{units:m}});
hAzzle.define("Setters",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Core"),f=hAzzle.require("Types"),q=hAzzle.require("has"),l=hAzzle.require("Strings"),m=Array.prototype.concat,d="width|height|x|y|cx|cy|r|rx|ry|x1|x2|y1|y2",t=/\S+/g,a=/\r/g,b=/^[\[\s]+|\s+|[\]\s]+$/g,p=/\s*[\s\,]+\s*/,u=/\\*\./g,g="multiple selected checked disabled readonly required async autofocus compact nowrap declare noshade hreflang onload srcnoresize defaultChecked autoplay controls defer autocomplete hidden tabindex readonly type accesskey dropzone spellcheck ismap loop scoped open".split(" "),
r={},n={},e={"class":"className","for":"htmlFor"},h={innerHTML:1,textContent:1,className:1,htmlFor:q.has("ie"),value:1},x={get:{},set:{}},v={get:{},set:{}},D={get:{},set:{}},w={get:{},set:{}},s={get:{},set:{}},z=function(a){return a instanceof hAzzle?a.elements:a},E=function(a,b){var c=r[b.toLowerCase()];return c&&n[a.nodeName]&&c},A=function(a,b){a=z(a);for(var c,d,f=0,h="string"===typeof b?b.match(t):m(b),g=h.length;f<g;f++)c=h[f],d=e[c]||c,E(a,c)?a[d]=!1:a.removeAttribute(c)},B=function(a,b,c){var d=
(a=z(a))?a.nodeType:void 0,e,g,m=h[b];if(!d||3===d||8===d||2===d)return"";if("undefined"===typeof a.getAttribute)return y(a,b,c);1===d&&k.isXML(a)||(b=b.toLowerCase(),e=x["undefined"===c?"get":"set"][b]||E(a,b)?w["undefined"===c?"get":"set"][b]:D["undefined"===c?"get":"set"][b]);if(void 0===c){if(e&&(g=e.get(a,b))&&null!==g)return g;if("textContent"==b)return y(a,b);g=a.getAttribute(b,2);return null==g?void 0:g}if(c){if(e&&void 0!==(g=e.set(a,c,b)))return g;if(m||"boolean"==typeof c||f.isFunction(c))return y(a,
b,c);a.setAttribute(b,c+"")}else A(a,b)},y=function(a,b,c){var d=(a=z(a))?a.nodeType:void 0,f,g;if(!d||3===d||8===d||2===d)return"";if(1!==d||k.isHTML)b=e[b]||b,f="undefined"===c?v.get[b]:v.set[b];return"undefined"!==typeof c?f&&void 0!==(g=f.set(a,c,b))?g:a[b]=c:f&&null!==(g=f(a,b))?g:a[b]};this.val=function(b){var d,e,g;e=this.elements[0];if(arguments.length)return g=f.isFunction(b),this.each(function(a,e){var h;1===a.nodeType&&(h=g?b.call(a,e,hAzzle(a).val()):b,null==h?h="":"number"===typeof h?
h+="":f.isArray(h)&&(h=c.map(h,function(a){return null==a?"":a+""})),d=s.set[a.type]||s.set[a.nodeName.toLowerCase()],d&&void 0!==d(a,h,"value")||(a.value=h))});if(e){if(d=s.get[e.type]||s.get[e.nodeName.toLowerCase()])return d(e,"value");e=e.value;return"string"===typeof e?e.replace(a,""):null==e?"":e}};this.hasAttr=function(a){return a&&"undefined"!==typeof this.attr(a)};this.toggleProp=function(a){return this.each(function(b){return b.prop(a,!b.prop(a))})};this.prop=function(a,b){var d=this.elements;
if("object"===typeof a)return this.each(function(b){c.each(a,function(a,c){y(b,c,a)})});if("undefined"===typeof b)return y(d[0],a);this.each(d,function(c){y(c,a,b)})};this.toggleProp=function(a){return this.each(function(b){return b.prop(a,!b.prop(a))})};this.removeProp=function(a){return this.each(function(){delete this[e[a]||a]})};this.removeAttr=function(a){return this.each(function(b){A(b,a)})};this.attr=function(a,b){var d=this.elements;return"object"===typeof a?this.each(function(b){c.each(a,
function(a,c){B(b,c,a)})}):"undefined"===typeof b?B(d[0],a):this.each(function(c){B(c,a,b)})};this.hasAttr=function(a){return a&&"undefined"!==typeof this.attr(a)};c.each(g,function(a){r[g[a]]=g[a]});c.each("input select option textarea button form details".split(" "),function(a){n[a.toUpperCase()]=!0});c.each("cellPadding cellSpacing maxLength rowSpan colSpan useMap frameBorder contentEditable textContent valueType tabIndex readOnly type accessKey tabIndex dropZone spellCheck hrefLang isMap srcDoc mediaGroup autoComplete noValidate radioGroup".split(" "),
function(a){e[a.toLowerCase()]=a});return{attrHooks:x,propHooks:v,boolHooks:w,nodeHooks:D,valHooks:s,propMap:e,boolAttr:r,boolElem:n,attr:B,prop:y,removeAttr:A,toggleAttr:function(a,b,c){a=z(a);"boolean"==typeof c||(c=null==B(a,b)===!1);var d=!c;c?B(a,b,""):A(a,b);return a[b]===d?a[b]=c:c},toAttrSelector:function(a,c,d){var e,f,h=0,g=0,k=[];c=!0===c;a="string"==typeof a?a.split(p):"number"==typeof a?""+a:a;for(e=a.length;h<e;)f=a[h++],(f=c?l.hyphenate(f):f.replace(b,""))&&(k[g++]=f);return!1===d?
k:g?"["+k.join("],[").replace(u,"\\\\.")+"]":""},getBooleanAttrName:E,SVGAttribute:function(a){if(q.ie||q.has("android")&&!q.has("chrome"))d+="|transform";return(new RegExp("^("+d+")$","i")).test(a)}}});
hAzzle.define("attrHooks",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Support"),f=hAzzle.require("Setters"),q=document.documentElement,l=window.document;c.mixin(f.attrHooks.set,{type:function(f,d){if(!k.radioValue&&"radio"===d&&c.nodeName(f,"input")){var l=f.value;f.setAttribute("type",d);l&&(f.value=l);return d}},title:function(c,d){(c=q?l:c).title=d}});c.mixin(f.attrHooks.get,{title:function(c){return c===q?l.title:c.title}});return{}});
hAzzle.define("propHooks",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Support"),f=hAzzle.require("Setters");c.mixin(f.propHooks.get,{tabIndex:function(c){return c.hasAttribute("tabindex")||focusable.test(c.nodeName)||c.href?c.tabIndex:-1}});k.optSelected||(f.propHooks.get.selected=function(c){(c=c.parentNode)&&c.parentNode&&c.parentNode.selectedIndex;return null});return{}});
hAzzle.define("boolHooks",function(){hAzzle.require("Setters").boolHooks.set=function(c,k,f){!1===k?removeAttr(c,f):c.setAttribute(f,f);return f};return{}});
hAzzle.define("valHooks",function(){var c=hAzzle.require("Util"),k=hAzzle.require("Strings"),f=hAzzle.require("Text"),q=hAzzle.require("Types"),l=hAzzle.require("Collection"),m=hAzzle.require("Setters");c.mixin(m.valHooks.set,{select:function(c,f){for(var a,b,k=c.options,m=l.makeArray(f),g=k.length;g--;)if(b=k[g],b.selected=0<=l.inArray(b.value,m))a=!0;a||(c.selectedIndex=-1);return m}});c.mixin(m.valHooks.get,{option:function(c){var l=c.getAttribute(name,2);return null!==l?l:k.trim(f.getText(c))},
select:function(d,f){for(var a,b=d.options,k=d.selectedIndex,l="select-one"===d.type||0>k,g=l?null:[],m=l?k+1:b.length,n=0>k?m:l?k:0;n<m;n++)if(a=b[n],!(!a.selected&&n!==k||null!==a.getAttribute("disabled")||a.parentNode.disabled&&c.nodeName(a.parentNode,"optgroup"))){f=hAzzle(a).val();if(l)return f;g.push(f)}return g}});c.each(["radio","checkbox"],function(c){m.valHooks.set[c]=function(c,a){if(q.isArray(a))return c.checked=0<=l.inArray(hAzzle(c).val(),a)}})});
hAzzle.define("Events",function(){var c=window,k=c.document,f=/[^\.]*(?=\..*)\.|.*/,q=/\..*/,l=/\S+/g,m=k.documentElement||{},d={},t=hAzzle.require("Util"),a=hAzzle.require("Collection"),b=hAzzle.require("Types"),p=hAzzle.require("Jiesa"),u=hAzzle.require("has"),g=hAzzle.require("Core"),r="altKey attrChange attrName bubbles cancelable ctrlKey currentTarget detail eventPhase getModifierState isTrusted metaKey relatedNode relatedTarget shiftKey srcElement target timeStamp type view which propertyName".split(" "),
n=r.concat("button buttons clientX clientY dataTransfer fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" ")),e=r.concat("char charCode key keyCode keyIdentifier keyLocation location".split(" "));u.has("firefox")&&r.concat(["mozMovementY","mozMovementX"]);u.has("webkit")&&r.concat(["webkitMovementY","webkitMovementX"]);var h={},x={},v={},D={},w=[{reg:/^key/,fix:function(a,b){b.which||(b.which=null!=a.charCode?a.charCode:a.keyCode);b.keyCode=a.keyCode||a.which;return e}},{reg:/^(?:mouse(?!(.*wheel|scroll))|pointer|menu|drag|drop|contextmenu)|click/,
fix:function(a,b,c){null==b.pageX&&null!=a.clientX&&(b.pageX=a.clientX+m.scrollLeft-m.clientLeft,b.pageY=a.clientY+m.scrollTop-m.clientTop);b.which||void 0===a.button||(b.which=a.button&1?1:a.button&2?3:a.button&4?2:0);if("mouseover"===c||"mouseout"===c)b.relatedTarget=a.relatedTarget||a[("mouseover"===c?"from":"to")+"Element"];return n}},{reg:/.*/,fix:function(){return r}}],s=function(b,c,d,e){var f=function(d,f){return c.apply(b,e?a.slice(f).concat(e):f)},h=d?function(a){var e=c.__kfx2rcf?c.__kfx2rcf.ft(a.target,
b):this;if(d.apply(e,arguments))return a&&(a.currentTarget=e),f(a,arguments)}:function(a){c.__kfx2rcf&&(a=a.clone(c.__kfx2rcf?c.__kfx2rcf.ft(a.target,b):void 0));return f(a,arguments)};h.__kfx2rcf=c.__kfx2rcf;return h},z=function(a,b,c,e,f,h){var g,k=f?"\u00a4":"#";if(b&&"*"!==b){f=0;g=d[k+b];var l="*"===a;if(g)for(k=g.length;f<k&&(!l&&!g[f].matches(a,c,e)||h(g[f],g,f,b));f++);}else for(g in d)g.charAt(0)===k&&z(a,g.slice(1),c,e,f,h)},E=function(a,b,c,e){if(e=d[(e?"\u00a4":"#")+b])for(b=e.length;b--;)if(!e[b].root&&
e[b].matches(a,c,null))return!0;return!1},A=function(a,b,c,d){var e=[];z(a,b,c,null,d,function(a){return e.push(a)});return e},B=function(a){z(a.element,a.type,null,a.handler,a.root,function(a,b,c){b.splice(c,1);a.removed=!0;0===b.length&&delete d[(a.root?"\u00a4":"#")+a.type];return!1})},y=function(a,b){var c=A(this,b||a.type,null,!1),d=c.length,e=0;a=new I(a,this,!0);b&&(a.type=b);for(;e<d&&!a.isImmediatePropagationStopped();e++)c[e].removed||c[e].handler.call(this,a)},C=function(a,b,c,d){b=b&&
b.replace(q,"");b=A(a,b,null,!1);var e={},f,g;f=0;for(g=b.length;f<g;f++)c&&b[f].original!==c||!b[f].inNamespaces(d)||(B(b[f]),e[b[f].eventType]||(e[b[f].eventType]={t:b[f].eventType,c:b[f].type}));for(f in e)E(a,e[f].t,null,!1)||a.removeEventListener(e[f].t,y,!1)},J=function(a,b,c,d,e){return function(){d.apply(this,arguments);a(b,c,e)}},K=function(a,b,c){if(c)for(var d="string"===typeof b?p.find(b,c,!0):c;a&&a!==c;a=a.parentElement)for(b=d.length;b--;)if(d[b]===a)return a},O=function(a,b){var c=
function(c){var d=c.target;d.nodeType&&!0!==d.disabled&&(d=K(d,a,this))&&b.apply(d,arguments)};c.__kfx2rcf={ft:K,selector:a};return c},G=function(c,e,g,k,m){c instanceof hAzzle&&(c=c.elements[0]);var n,p,t,r,s,u;if("object"===b.isType(e))for(p in"string"!==typeof g&&(k=g,g=void 0),e)G(c,p,e[p]);else{b.isType("Function")(g)?(r=a.slice(arguments,3),k=n=g):(n=k,r=a.slice(arguments,4),k=O(g,n));"function"!==typeof k&&hAzzle.err(!0,13,"no handler registred for on() in events.js module");e=(e||"").match(l)||
[""];m&&(k=J(H,c,e,k,n));for(t=e.length;t--;)if(p=e[t].replace(q,"")){s=e[t].replace(f,"").split(".");s=p=new F(c,p,k,n,s,r,!1);var v=!s.root&&!E(s.element,s.type,null,!1),w=(s.root?"\u00a4":"#")+s.type;(d[w]||(d[w]=[])).push(s);if(s=v)p=p.eventType,(u=h[p])&&u(c,p),c.addEventListener(p,y,!1)}return c}},L=function(a,b,c,d){return G(a,b,c,d,1)},H=function(a,c,d){a instanceof hAzzle&&(a=a.elements[0]);var e,g;if("string"===typeof c&&0<c.indexOf(" ")){c=(c||"").match(l)||[""];for(g=c.length;g--;)H(a,
c[g],d);return a}(g="string"===typeof c&&c.replace(q,""))&&v[g]&&(g=v[g].base);if(c&&"string"!==typeof c)if(b.isType("Function")(c))C(a,null,c);else for(e in c)H(a,e,c[e]);else{if(c="string"===typeof c&&c.replace(f,""))c=c.split(".");C(a,g,d,c)}return a},M=function(a,b,c){a instanceof hAzzle&&(a=a.elements[0]);if(3!==a.nodeType&&8!==a.nodeType){var d=(b||"").match(l)||[""],e,g,h;for(e=d.length;e--;){b=d[e].replace(q,"");if(h=d[e].replace(f,""))h=h.split(".");if(h&&c){g=new I(null,a);g.type=b;c=c?
[g].concat(c):g;d=0;for(e=(void 0).length;d<e;d++)(void 0)[d].inNamespaces(h)&&(void 0)[d].handler.call(a,c);d=!1!==g.returnValue}else d=k.createEvent("HTMLEvents"),d.detail=arguments,d.initEvent(b,!0,!0),d=a.dispatchEvent(d);return d}return a}},N=function(a,b,c){b=A(b,c,null,!1);c=b.length;for(var d=0,e,f;d<c;d++)b[d].original&&(e=[a,b[d].type],(f=b[d].handler.__kfx2rcf)&&e.push(f.selector),e.push(b[d].original),G.apply(null,e));return a},I=function(a,b){if(this.originalEvent=a=a||((b.ownerDocument||
b.document||b).parentWindow||c).event){a.target||(a.target=document);var d=a.type,e=a.target||a.srcElement,f,g,h;this.target=3===e.nodeType?e.parentNode:e;this.timeStamp=Date.now();h=D[d];if(!h){h=x[d];if(!h)for(e=0,f=w.length;e<f;e++)if(w[e].reg.test(d)){x[d]=h=w[e].fix;break}d=h(a,this,d);for(e=d.length;e--;)!((g=d[e])in this)&&g in a&&(this[g]=a[g])}}};I.prototype={constructor:I,preventDefault:function(){var a=this.originalEvent;a&&a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=
this.originalEvent;a&&a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},stop:function(){this.preventDefault();this.stopPropagation();this.stopped=!0},stopImmediatePropagation:function(){var a=this.originalEvent;a.stopImmediatePropagation&&a.stopImmediatePropagation();this.isImmediatePropagationStopped=function(){return!0}},isImmediatePropagationStopped:function(){var a=this.originalEvent;return a.isImmediatePropagationStopped&&a.isImmediatePropagationStopped()},clone:function(a){var b=new I(this,
this.element);b.currentTarget=a;return b}};var F=function(a,b,c,d,e,f,g){return new F.prototype.init(a,b,c,d,e,f,g)};F.prototype={constructor:F,init:function(a,b,c,d,e,f,g){var h=v[b];"unload"===b&&(c=J(C,a,b,c,d));h&&(h.condition&&(c=s(a,c,h.condition,f)),b=h.base||b);this.element=a;this.type=b;this.original=d;this.namespaces=e;this.eventType=b;this.target=a;this.root=g;this.handler=s(a,c,null,f)},inNamespaces:function(a){var b,c,d=0;if(!a)return!0;if(!this.namespaces)return!1;for(b=a.length;b--;)for(c=
this.namespaces.length;c--;)a[b]===this.namespaces[c]&&d++;return a.length===d},matches:function(a,b,c){return this.element===a&&(!b||this.original===b)&&(!c||this.handler===c)}};F.prototype.init.prototype=F.prototype;this.on=function(a,b,c){this.each(function(d){G(d,a,b,c)})};this.one=function(a,b,c){this.each(function(d){L(d,a,b,c)})};this.off=function(a,b){this.each(function(c){H(c,a,b)})};this.trigger=function(a,b){this.each(function(c){M(c,a,b)})};this.cloneEvents=function(a,b){N(this.elements[0],
a,b)};this.hover=function(a,b){return this.mouseenter(a).mouseleave(b||a)};t.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){v[b]={base:a,condition:function(a){return(a=a.relatedTarget)?a!==this&&!g.contains(a,this):null==a}}});t.each("blur change click dblclick error focus focusin focusout keydown keypress keyup load mousedown mouseenter mouseleave mouseout mouseover mouseup mousemove resize scroll select submit unload change contextmenu".split(" "),
function(a){this[a]=function(b){return 0<arguments.length?this.on(a,b):this.trigger(a)}}.bind(this));return{specialEvents:h,propHooks:w,mouseProps:n,commonProps:r,addEvent:function(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)},removeEvent:function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)},on:G,one:L,off:H,clone:N,trigger:M}});
hAzzle.define("specialEvents",function(){var c=hAzzle.require("Util"),k=hAzzle.require("has"),f=hAzzle.require("Events");if(k.has("firefox")){var q=function(f,k){var d,q="focusin"===k?"focus":"blur",a=function(a){var b=hAzzle(a).find("input").elements;a=hAzzle(a).find("select").elements;a.length&&push.apply(b,a);return b}(f),b=function(a){return function(){if(this===document.activeElement&&this.blur)return hAzzle(this).trigger(a),!1}}(k),p=-1,u=a.length;for(d="__"+q+"fixed__";++p<u;)c.has(a[p],d)&&
a[p][d]||(a[p][d]=!0,a[p].addEventListener(q,b,!0))};c.each(["focusin","focusout"],function(c){f.specialEvents[c]=q})}return{}});
hAzzle.define("eventHooks",function(){var c=hAzzle.require("Events"),k=c.mouseProps.concat("wheelDelta wheelDeltaX wheelDeltaY wheelDeltaZ deltaY deltaX deltaZ".split(" ")),f=c.commonProps.concat(["data"]),q=c.commonProps.concat(["touches","changedTouches","targetTouches","scale","rotation"]),l=c.commonProps.concat(["data","origin","source"]),m=c.commonProps.concat(["state"]);c.propHooks=c.propHooks.concat([{reg:/mouse.*(wheel|scroll)/i,fix:function(){return k}},{reg:/^text/i,fix:function(){return f}},
{reg:/^touch|^gesture/i,fix:function(){return q}},{reg:/^message$/i,fix:function(){return l}},{reg:/^popstate$/i,fix:function(){return m}}]);return{}});
(function(c){function k(d){return"string"===typeof d?c.document.createTextNode(d):d}function f(d){var a=c.document.createDocumentFragment(),b=q.call(d,0),f=0,l=d.length;if(1===d.length)return k(d[0]);for(;f<l;f++)try{a.appendChild(k(b[f]))}catch(g){}return a}for(var q=Array.prototype.slice,l=(c.Element||c.Node||c.HTMLElement).prototype,m=["append",function(){this.appendChild(f(arguments))},"prepend",function(){this.firstChild?this.insertBefore(f(arguments),this.firstChild):this.appendChild(f(arguments))},
"before",function(){var c=this.parentElement;c&&c.insertBefore(f(arguments),this)},"after",function(){this.parentElement&&(this.nextSibling?this.parentElement.insertBefore(f(arguments),this.nextSibling):this.parentElement.appendChild(f(arguments)))},"replace",function(){this.parentElement&&this.parentElement.replaceChild(f(arguments),this)},"remove",function(){this.parentElement&&this.parentElement.removeChild(this)},"matches",l.matchesSelector||l.webkitMatchesSelector||l.mozMatchesSelector||l.msMatchesSelector||
function(c){var a=this.parentElement;return!!a&&-1<indexOf.call(a.querySelectorAll(c),this)}],d=m.length;d;d-=2)m[d-2]in l||(l[m[d-2]]=m[d-1])})(window);