(function(a,s){if(!a.hAzzle){var n=a.document,d=a.document.documentElement,c=Array.prototype,e=c.push,k=c.slice,p=c.splice,w=c.concat,r=Object.prototype.toString,c=Date.now||function(){return(new Date).getTime()},u={current:0,next:function(){return++this.current}},t=[],x=[],v={},y=n.createElement("div"),l=function(b,a){return new l.fn.init(b,a)},f=l.support={};f.classList=!!n.createElement("p").classList;y.style.backgroundClip="content-box";y.cloneNode(!0).style.backgroundClip="";f.clearCloneStyle=
"content-box"===y.style.backgroundClip;l.fn=l.prototype={init:function(b,a){var g,h;if(b instanceof l)return b;if(l.isString(b))if("<"===b[0]&&">"===b[b.length-1]&&3<=b.length)this.elems=l.parseHTML(b,a&&a.nodeType?a.ownerDocument||a:n,!0);else{if(x[b]&&!a){this.elems=g=x[b];for(h=this.length=g.length;h--;)this[h]=g[h];return this}this.elems=x[b]=l.select(b,a)}else{if(l.isFunction(b)){if(l.ready)return l.ready(b);console.log("The DOM Ready module are not installed!!");return[]}if(b instanceof Array)this.elems=
l.unique(b.filter(l.isElement));else{if(l.isObject(b))return this.elems=[b],this.length=1,this[0]=b,this;l.isNodeList(b)?this.elems=k.call(b).filter(l.isElement):l.isElement(b)?this.elems=[b]:this.elems=[]}}g=this.elems;for(h=this.length=g.length;h--;)this[h]=g[h];return this},each:function(b,a){return l.each(this,b,a)},find:function(b){if("string"===typeof b){var a;a=1===this.length?"string"!==typeof b?b[0]:l(b,this.elems):this.elems.reduce(function(h,a){return h.concat(l.select(b,a))},[]);return l.create(a)}if("object"===
typeof b){var g=this;a=l(b).filter(function(){var b=this;return g.elems.some.call(g,function(a){return l.contains(a,b)})});return l.create(a)}return this},filter:function(b,a){if("function"===typeof b){var g=b;return l.create(this.elems.filter(function(b,m){return g.call(b,b,m)!==(a||!1)}))}b&&"!"===b[0]&&(b=b.substr(1),a=!0);return l.create(this.elems.filter(function(h){return l.matches(h,b)!==(a||!1)}))},contains:function(b){var a;return l.create(this.elems.reduce(function(g,h){a=l.select(b,h);
return g.concat(a.length?h:null)},[]))},pluck:function(b,a){return l.pluck(this.elems,b,a)},put:function(b,a,g){return l.put(this.elems,b,a,g)},get:function(b){return arguments.length?this.elems[0>b?this.elems.length+b:b]:this.elems.slice()},map:function(b){for(var a=[],g=this.elems,h=0,m=g.length;h<m;h++)a.push(b(g[h]));return l(a)},sort:function(b){return l(this.elems.sort(b))},concat:function(){var b=k.call(arguments).map(function(b){return b instanceof l?b.elements:b});return l(w.apply(this.elems,
b))},slice:function(b,a){return l(k.call(this.elems,b,a))},splice:function(b,a){return l(p.call(this.elems,b,a))},push:function(b){return l.isElement(b)?(this.elems.push(b),this.length=this.elems.length,this.length-1):-1},indexOf:function(b){return l.indexOf(this.elems,b||"")},unique:function(){return l.unique(this.elems)},reduce:function(b,a){var g=this.elems,h=g.length,m,q;if(!h)return a;1===arguments.length?(m=g[0],q=1):(m=a,q=0);for(;q<h;)q in g&&(m=b(m,g[q],q,g)),++q;return m},reduceRight:function(b,
a,g,h){return this.elems.reduceRight.call(b,a,g,h)},compact:function(b){return this.filter(b,function(b){return!!b})},iterate:function(b,a){return function(g,h,m,q){return this.each(function(){b.call(a,this,g,h,m,q)})}},eq:function(b){if(arguments)return l(this.get(b))}};l.fn.init.prototype=l.fn;l.extend=l.fn.extend=function(){var b=arguments[0]||{};"object"!==typeof b&&"function"!==typeof b&&(b={});1===arguments.length&&(b=this);for(var a=k.call(arguments),g,h=a.length;h--;){g=a[h];for(var m in g)b[m]!==
g[m]&&(b[m]=g[m])}return b};l.extend({each:function(b,a){var g=0,h,m=b.length;if(b.length===+b.length)for(;g<m&&!1!==a.call(b[g],g,b[g++]););else for(h in b)if(!1===a.call(b[h],h,b[h]))break;return b},type:function(b){return r.call(b)},is:function(b,a){return 0<=l.indexOf(b,this.type(a))},isElement:function(b){return b&&(v[1](b)||v[9](b)||!+b.nodeType)},isNodeList:function(b){return b&&this.is(["nodelist","htmlcollection","htmlformcontrolscollection"],b)},IsNaN:function(b){return l.isNumber(b)&&b!=
+b},isUndefined:function(b){return"undefined"===typeof b},isDefined:function(b){return"undefined"!==typeof b},isString:function(b){return"string"===typeof b},isFunction:function(b){return"function"===typeof b},isNumber:function(b){return"number"===typeof b},isObject:function(b){return b===Object(b)},isNumeric:function(b){return!l.isArray(b)&&0<=b-parseFloat(b)},isEmptyObject:function(b){for(var a in b)return!1;return!0},isArray:Array.isArray,isArrayLike:function(b){if(null===b||l.isWindow(b))return!1;
var a=b.length;return v[1](b)&&a?!0:l.isString(b)||l.isArray(b)||0===a||"number"===typeof a&&0<a&&a-1 in b},likeArray:function(a){return"number"===typeof a.length},isWindow:function(a){return a&&a.document&&a.location&&a.alert&&a.setInterval},isFile:function(a){return"[object File]"===r.call(a)},isBlob:function(a){return"[object Blob]"===r.call(a)},isDocument:function(a){return null!==a&&a.nodeType==a.DOCUMENT_NODE},isNull:function(a){return null===a},isBoolean:function(a){return"boolean"===typeof a},
error:function(a){throw Error(a);},unique:function(a){return a.filter(function(f,g){return l.indexOf(a,f)===g})},create:function(a,f){return"undefined"===typeof f?l(a):l(a).filter(f)},prefix:function(b,f){var g,h=b[0].toUpperCase()+b.slice(1),m,q=["moz","webkit","ms","o"];f=f||a;if(g=f[b])return g;for(;(m=q.shift())&&!(g=f[m+h]););return g},pluck:function(a,f,g){return a.map(function(a){g&&v[g](a);return a[f]})},contains:function(a,f){if(d.compareDocumentPosition){var g=v[9](a)?a.documentElement:
a,h=f&&f.parentNode;return a===h||!!(h&&v[1](h)&&(g.contains?g.contains(h):a.compareDocumentPosition&&a.compareDocumentPosition(h)))}if(f)for(;f=f.parentNode;)if(f===a)return!0;return!1},indexOf:function(a,f){for(var g=0,h;h=a[g];g+=1)if(f===h)return g;return!1},now:c,nodeType:function(a,f){return v[a]?v[a](f):!1},trim:function(){return String.prototype.trim?function(a){return"string"===typeof a?a.trim():a}:function(a){return"string"===typeof a?a.replace(/^\s\s*/,"").replace(/\s\s*$/,""):a}}(),inArray:function(a,
f){return l.indexOf(a,f)},getUID:function(a){if(l.isDefined(a))return a.hAzzle_id||(a.hAzzle_id=u.next())},put:function(a,f,g,h){return l.each(a,function(m){l.isDefined(h)&&null!==a&&l.nodeType(h,a);a[m][f]=g})},merge:function(a,f){for(var g=+f.length,h=0,m=a.length;h<g;)a[m++]=f[h++];if(g!==g)for(;f[h]!==s;)a[m++]=f[h++];a.length=m;return a},delay:function(a,f){var g=k.call(arguments,2);return setTimeout(function(){return a.apply(null,g)},f)},defer:function(a){return l.delay.apply(l,[a,1].concat(k.call(arguments,
1)))},once:function(a){var f=!1,g;return function(){if(f)return g;f=!0;g=a.apply(this,arguments);a=null;return g}},nodeName:function(a,f){return a.nodeName&&a.nodeName.toLowerCase()===f.toLowerCase()},camelCase:function(a){t[a]||(t[a]=a.replace(/^-ms-/,"ms-").replace(/^.|-./g,function(a,b){return 0===b?a.toLowerCase():a.substr(1).toUpperCase()}));return t[a]},map:function(a,f){var g,h=[],m;if(l.likeArray(a))for(m=a.length;m--;)g=f(a[m],m),null!==g&&h.push(g);else for(m in a)g=f(a[m],m),null!==g&&
h.push(g);return h},isXML:function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},grep:function(a,f,g,h){var m=[],q;g=!!g;for(var k=0,c=a.length;k<c;k++)k in a&&(q=!!f.call(h,a[k],k),g!==q&&m.push(a[k]));return m},toArray:function(){return k.call(this,0)},makeArray:function(a,f){var g=f||[];null!==a&&(l.isArraylike(Object(a))?l.merge(g,"string"===typeof a?[a]:a):e.call(g,a));return g},noop:function(){}});l.each("1 2 3 4 5 6 7 8 9 10 11 12".split(" "),function(a){v[a]=
function(f){return f.nodeType===a}});l.each(["Arguments","Function","Date","RegExp"],function(a,f){l["is"+f]=function(a){return r.call(a)=="[object "+f+"]"}});"undefined"===typeof a.hAzzle&&(a.hAzzle=l)}})(window);
(function(a){function s(a){return a?"string"===typeof a?hAzzle.select(a)[0]:!a[c]&&"object"===typeof a&&isFinite(a.length)?a[0]:a:d}var n=Array.prototype.slice,d=document,c="nodeType",e={idClassTagNameExp:/^(?:#([\w-]+)|\.([\w-]+)|(\w+))$/,tagNameAndOrIdAndOrClassExp:/^(\w+)(?:#([\w-]+)|)(?:\.([\w-]+)|)$/,pseudos:/(.*):(\w+)(?:\(([^)]+)\))?$\s*/};hAzzle.extend({pseudos:{disabled:function(){return!0===this.disabled},enabled:function(){return!1===this.disabled&&"hidden"!==this.type},selected:function(){this.parentNode&&
this.parentNode.selectedIndex;return!0===this.selected},checked:function(){var a=this.nodeName.toLowerCase();return"input"===a&&!!this.checked||"option"===a&&!!this.selected},parent:function(){return this.parentNode},first:function(a){if(0===a)return this},last:function(a,c){if(a===c.length-1)return this},empty:function(){var a;for(a=this.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},eq:function(a,c,e){if(a===e)return this},contains:function(a,c,e){if(-1<hAzzle(this).text().indexOf(e))return this},
has:function(a,c,e){if(hAzzle.qsa(this,e).length)return this},radio:function(){return"radio"===this.type},checkbox:function(){return"checkbox"===this.type},file:function(){return"file"===this.type},password:function(){return"password"===this.type},submit:function(){return"submit"===this.type},image:function(){return"image"===this.type},button:function(){var a=this.nodeName.toLowerCase();return"input"===a&&"button"===this.type||"button"===a},target:function(){var a=window.location&&window.location.hash;
return a&&a.slice(1)===this.id},input:function(){return/input|select|textarea|button/i.test(this.nodeName)},focus:function(){return this===document.activeElement&&(!document.hasFocus||document.hasFocus())&&!!(this.type||this.href||~this.tabIndex)}},qsa:function(a,c){try{return c.querySelectorAll(a)}catch(e){console.error("error performing selector: %o",a)}},select:function(a,c){var d,r=[];c=s(c);if(d=e.idClassTagNameExp.exec(a))if(a=d[1])r=(r=c.getElementById(a))?[r]:[];else if(a=d[2])r=c.getElementsByClassName(a);
else{if(a=d[3])r=c.getElementsByTagName(a)}else if(d=e.tagNameAndOrIdAndOrClassExp.exec(a)){var u=c.getElementsByTagName(d[1]),t=d[2],x=d[3];hAzzle.each(u,function(a,f){var b;(b=f.id===t)||(b=hAzzle.support.classList?f.classList.contains(x):hAzzle.contains((""+f.className).split(" "),x));b&&r.push(f)})}else if(d=e.pseudos.exec(a)){var v=hAzzle.pseudos[d[2]],y=d[3];a=this.qsa(d[1],c);r=hAzzle.unique(hAzzle.map(a,function(c,f){try{return v.call(c,f,a,y)}catch(b){console.error("error performing selector: %o",
a)}}))}else r=this.qsa(a,c);return hAzzle.isNodeList(r)?n.call(r):hAzzle.isElement(r)?[r]:r},getChildren:function(a,c){var e=a.getElementsByTagName?a.getElementsByTagName(c||"*"):a.querySelectorAll?a.querySelectorAll(c||"*"):[];return void 0===c||c&&hAzzle.nodeName(a,c)?hAzzle.merge([a],e):e}})})(hAzzle);
(function(a){var s=document,n=s.createElement("div");a.extend(a,{matches:function(a,c){var e,k,p=function(a,c){c.parentNode||n.appendChild(c);k=0<=hAzzle.indexOf(hAzzle.select(a,c.parentNode),c);c.parentNode===n&&n.removeChild(c);return k};return a&&hAzzle.isElement(a)&&c?c.nodeType?a===c:c instanceof hAzzle?c.elems.some(function(c){return hAzzle.matches(a,c)}):a===s?!1:(e=hAzzle.prefix("matchesSelector",n))&&(cached[c]?cached[c]:cached[c]=e.call(n,"div"))&&!hAzzle.nodeType(11,a)?e.call(a,c):p(c,
a):!1}})})(hAzzle);(function(a){function s(){if(!d){d=!0;for(var a=0;a<n.length;a++)n[a].fn.call(window,n[a].ctx);n=[]}}var n=[],d=!1,c=!1;a.extend({ready:function(a,k){k=k||document;d?setTimeout(function(){a(k)},1):(n.push({fn:a,ctx:k}),"complete"===document.readyState?setTimeout(s,1):c||(document.addEventListener("DOMContentLoaded",s,!1),window.addEventListener("load",s,!1),c=!0))}})})(hAzzle);
(function(a){var s=[],n=Array.prototype.slice;a.extend(a.fn,{pluckNode:function(d){return this.map(function(c){return a.getClosestNode(c,d)})},closest:function(d,c){return this.map(function(e){return a.nodeType(1,e)&&e!==c&&!a.isDocument(e)&&a.matches(e,"object"==typeof d?a(d):d)?e:a.getClosestNode(e,"parentNode",d,11)})},index:function(d){return d?this.indexOf(a(d)[0]):this.parent().children().indexOf(this[0])||-1},selectedIndex:function(d){if(a.isArray(d)){for(var c=[],e=0,e=d.length;e--;)c.push(this.get(d[e]));
return a(c)}},tags:function(d){return this.map(function(c){if(c.tagName.toLowerCase()===d&&a.nodeType(1,c))return c})},add:function(d,c){if(1===arguments.length)return d=a(d,c).elems,this.concat(d)},has:function(d){var c=a(d,this),e=c.length;return this.filter(function(){for(var d=0;d<e;d++)if(a.contains(this,c[d]))return!0})},not:function(a){return this.filter(a||[],!0)},is:function(a){return 0<this.length&&0<this.filter(a||[]).length},parent:function(d){return a(this.pluck("parentNode",11),d)},
parents:function(d){for(var c=[],e=this.elems,k=function(e){if((e=e.parentNode)&&e!==document&&0>c.indexOf(e)&&a.nodeType(1,e))return c.push(e),e};0<e.length&&void 0!==e[0];)e=e.map(k);return a.create(c,d)},children:function(d){return a(this.reduce(function(c,e){if(a.nodeType(1,e))return c.concat(n.call(e.children))},[]),d)},next:function(d){return d?a(this.pluckNode("nextSibling").filter(d)):a(this.pluckNode("nextSibling"))},nextOfClass:function(a){var c,e=this;for("."===a[0]&&(a=a.slice(1));e.next();){if(e.hasClass(a))return e;
c=e.next();if(0===c.length)e=e.parent();else if(e=c,0===e.parent().length)return!1}},nextUntil:function(d){var c=[];this.nextAll().each(function(){if(a(this).is(d))return!1;c.push(this)});return a(c)},prev:function(d){return d?a(this.pluckNode("previousSibling").filter(d)):a(this.pluckNode("previousSibling"))},prevUntil:function(d){var c=[];this.prevAll().each(function(){if(a(this).is(d))return!1;c.push(this)});return a(c)},first:function(){return a(this.get(0))},last:function(){return a(this.get(-1))},
contents:function(){return this.map(function(a){return a.contentDocument||n.call(a.childNodes)})},siblings:function(d){var c=[];s[d]||(this.each(function(e,d){a.each(n.call((d.parentNode||{}).childNodes),function(e,n){a.isElement(n)&&a.nodeType(1,n)&&n!==d&&c.push(n)})}),s[d]=c);return a.create(s[d],d)}});a.extend(a,{getClosestNode:function(d,c,e,k){do d=d[c];while(d&&(e&&!a.matches(e,d)||!a.isElement(d)));a.isDefined(k)&&null!==d&&a.nodeType(k,d);return d}});a.each({nextAll:"next",prevAll:"prev"},
function(d,c){a.fn[d]=function(e){for(var d=a(),p=this[c]();p.length;){if("undefined"===typeof e||p.is(e))d=d.add(p);p=p[c]()}return d}})})(hAzzle);
(function(a){function s(f){return a.nodeType(1,f)||a.nodeType(9,f)||a.nodeType(11,f)?!0:!1}function n(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function d(a){var b=v.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}var c={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},
e={multiple:!0,selected:!0,checked:!0,disabled:!0,readOnly:!0,required:!0,open:!0},k={input:!0,select:!0,option:!0,textarea:!0,button:!0,form:!0,details:!0},p=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,w=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,r=/<([\w:]+)/,u=/<|&#?\w+;/,t=/checked\s*(?:[^=]|=\s*.checked.)/i,x=/^$|\/(?:java|ecma)script/i,v=/^true\/(.*)/,y=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,l=[];a.extend(a,{htmlHooks:{regex:/<([\w:]+)/,option:function(){return[1,"<select multiple='multiple'>",
"</select>"]},thead:function(){return[1,"<table>","</table>"]},col:function(){return[2,"<table><colgroup>","</colgroup></table>"]},tr:function(){return[2,"<table><tbody>","</tbody></table>"]},td:function(){return[3,"<table><tbody><tr>","</tr></tbody></table>"]}},Hooks:{SELECT:function(f){for(var b,c=f.options,g=f.selectedIndex,h=(f="select-one"===f.type||0>g)?null:[],m=f?g+1:c.length,q=0>g?m:f?g:0;q<m;q++)if(b=c[q],!(!b.selected&&q!==g||b.disabled||b.parentNode.disabled&&a.nodeName(b.parentNode,"optgroup"))){b=
a(b).val();if(f)return b;h.push(b)}return h},OPTION:function(f){var b=a(f).filter(function(a){return a.selected&&!a.disabled}).pluck("value");return null!==b?b:a.trim(getText(f))}},getText:function(f){var b,c="",g=0;if(!f.nodeType)for(;b=f[g++];)c+=a.getText(b);else if(s(f)){if(a.isString(f.textContent))return f.textContent;for(f=f.firstChild;f;f=f.nextSibling)c+=a.getText(f)}else if(a.nodeType(3,f)||a.nodeType(4,f))return f.nodeValue;return c},prop:function(f,b,e){if(!(a.nodeType(2,f)||a.nodeType(3,
f)||a.nodeType(8,f)))return b=c[b]||b,"undefined"!==typeof e?f[b]=e:f[b]},attr:function(f,b,c){if(!(a.nodeType(2,f)||a.nodeType(3,f)||a.nodeType(8,f))){if("undefined"===typeof f.getAttribute)return a.prop(f,b,c);if("undefined"===typeof c){if(a.Hooks[f.nodeName])return a.Hooks[f.nodeName](f);f=f.getAttribute(b,2);return null===f?void 0:f}if("SELECT"===f.nodeName){var g;b=f.options;for(var h=a.makeArray(c),m=b.length;m--;)if(c=b[m],c.selected=0<=a.inArray(c.value,h))g=!0;g||(f.selectedIndex=-1);return h}return f.setAttribute(b,
c+"")}},Evaluated:function(f,b){for(var c=0,g=f.length;c<g;c++)a.data(f[c],"evaluated",!b||a.data(b[c],"evaluated"))},parseHTML:function(f,b,c){if(!f||"string"!==typeof f)return null;"boolean"===typeof b&&(c=b,b=!1);b=b||document;var g=w.exec(f);c=!c&&[];if(g)return[b.createElement(g[1])];g=a.createHTML([f],b,c);c&&c.length&&a(c).remove();return a.merge([],g.childNodes)},createHTML:function(f,b,c,g){var h,m,q,e,A,l=b.createDocumentFragment(),d=[],k=0;a.each(f,function(g,c){if(c||0===c)if("object"===
typeof c)a.merge(d,c.nodeType?[c]:c);else if(u.test(c)){h=h||l.appendChild(b.createElement("div"));m=(a.htmlHooks.regex.exec(c)||["",""])[1].toLowerCase();q=a.htmlHooks[m]||[0,"",""];h.innerHTML=q[1]+c.replace(p,"<$1></$2>")+q[2];for(A=q[0];A--;)h=h.lastChild;a.merge(d,h.childNodes);h=l.firstChild;h.textContent=""}else d.push(b.createTextNode(c))});l.textContent="";for(k=0;f=d[k++];)if(!g||-1!==a.indexOf.call(g,f))if(e=a.contains(f.ownerDocument,f),h=a.getChildren(l.appendChild(f),"script"),e&&a.Evaluated(h),
c)for(A=0;f=h[A++];)x.test(f.type||"")&&c.push(f);return l}});a.extend(a.fn,{text:function(c,b){if(arguments.length)this.empty().each(function(){s(this)&&("undefined"!==typeof HTMLElement&&HTMLElement.prototype.insertAdjacentText?this.insertAdjacentText("beforeEnd",c):this.textContent=c)});else return a.getText(this)},html:function(c,b){return!arguments.length&&a.nodeType(1,this[0])?this[0].innerHTML:this.each(function(e,g){b&&a.nodeType(1,g)?g.insertAdjacentHTML("beforeend",c||""):!a.nodeType(1,
g)||"string"!==typeof c||/<(?:script|style|link)/i.test(c)||a.htmlHooks[(r.exec(c)||["",""])[1].toLowerCase()]||(c=l[c]?l[c]:l[c]=c.replace(/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,"<$1></$2>"),a(g).removeData(),g.textContent="",g.innerHTML=c)})},val:function(c){if(arguments.length)return this.each(function(b,g){var h;a.nodeType(1,g)&&(h=a.isFunction(c)?c.call(g,b,a(g).val()):c,null===h?h="":"number"===typeof h&&(h+=""),g.value=h)});var b=this[0];return a.Hooks[b.tagName]?
a.Hooks[b.tagName](b):b.value},attr:function(c,b){return a.isObject(c)?this.each(function(b,g){a.each(c,function(h,m){a.attr(g,h,m)})}):a.isUndefined(b)?a.attr(this[0],c):1===this.length?a.attr(this[0],c,b):this.each(function(){return a.attr(this,c,b)})},removeAttr:function(f){var b,l,g=0,h=f&&f.match(/\S+/g);return this.each(function(m,q){if(h&&a.nodeType(1,q))for(;b=h[g++];){l=c[b]||b;var f=q,A=e[b.toLowerCase()];A&&k[f.nodeName]&&A&&(q[l]=!1);q.removeAttribute(b)}})},prop:function(f,b){return a.isObject(f)?
this.each(function(b,g){a.each(f,function(h,m){a.prop(g,h,m)})}):"undefined"===typeof b?this[0]&&this[0][c[f]||f]:a.prop(this[0],key,b)},removeProp:function(a){return this.each(function(){delete this[c[a]||a]})},replaceWith:function(a){if("string"===typeof a)return this.before(a).remove();var b=arguments[0];this.manipulateDOM(arguments,function(a){(b=this.parentNode)&&b.replaceChild(a,this)});return b&&(b.length||b.nodeType)?this:this.remove()},appendTo:function(c){return this.each(function(){a(c).append(this)})},
prependTo:function(c){return this.each(function(){a(c).prepend(this)})},manipulateDOM:function(c,b){c=concat.apply([],c);var e,g,h,m,q=0,z=this.length,l=this,k=z-1,p=c[0],s=a.isFunction(p);if(s||1<z&&"string"===typeof p&&!support.checkClone&&t.test(p))return this.each(function(a){var h=l.eq(a);s&&(c[0]=p.call(this,a,h.html()));h.manipulateDOM(c,b)});if(z&&(e=a.createHTML(c,this[0].ownerDocument,!1,this),g=e.firstChild,1===e.childNodes.length&&(e=g),g)){g=a.map(a.getChildren(e,"script"),n);for(h=g.length;q<
z;q++)m=e,q!==k&&(m=a.clone(m,!0,!0),h&&a.merge(g,a.getChildren(m,"script"))),b.call(this[q],m,q);if(h)for(e=g[g.length-1].ownerDocument,a.map(g,d),q=0;q<h;q++)m=g[q],x.test(m.type||"")&&!a.data(m,"evaluated")&&a.contains(e,m)&&(m.src?a._evalUrl&&a._evalUrl(m.src):a.Evaluated(m.textContent.replace(y,"")))}return this},wrap:function(c){a.isFunction(c);return this.each(function(b){a(this).wrapAll(a.isFunction(c)?c.call(this,b):c)})},wrapAll:function(c){if(this[0]){a(this[0]).before(c=a(c,this[0].ownerDocument).eq(0).clone(!0));
for(var b;(b=c.children()).length;)c=b.first();a(c).append(this)}return this},wrapInner:function(c){return a.isFunction(c)?this.each(function(b){a(this).wrapInner(c.call(this,b))}):this.each(function(){var b=a(this),e=b.contents();e.length?e.wrapAll(c):b.append(c)})},unwrap:function(){this.parent().each(function(){a.nodeName(this,"body")||a(this).replaceWith(a(this).children()).remove()});return this}});a.each(["optgroup","tbody","tfoot","colgroup","caption"],function(c){a.htmlHooks[c]=function(){return a.htmlHooks.thead}});
a.each({prepend:"afterbegin",append:"beforeend"},function(c,b){a.fn[c]=function(e){return"string"===typeof e?this.each(function(a,h){s(this)&&h.insertAdjacentHTML(b,e)}):this.manipulateDOM(arguments,function(b){if(s(this)){var h=a.nodeName(this,"table")&&a.nodeName(a.nodeType(11,b)?b:b.firstChild,"tr")?this.getElementsByTagName("tbody")[0]||b.appendChild(this.ownerDocument.createElement("tbody")):this;"prepend"===c?h.insertBefore(b,h.firstChild):h.appendChild(b)}})}});a.each({before:"beforebegin",
after:"afterend"},function(c,b){a.fn[c]=function(e){return a.isString(e)?this.each(function(){this.insertAdjacentHTML(b,e)}):this.manipulateDOM(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,"after"===c?this:this.nextSibling)})}})})(hAzzle);
(function(a){function s(a){if(a=a.relatedTarget){var m;if(m=a!==this)if(m="xul"!==a.prefix)if(m=!/document/.test(this.toString())){a:{for(;a=a.parentNode;)if(a===this){a=1;break a}a=0}m=!a}a=m}else a=null===a;return a}function n(a){return a}function d(h,m){if(!(this instanceof d))return new d(h,m);if(arguments.length&&(this.originalEvent=h=h||((m.ownerDocument||m.document||m).parentWindow||c).evt)){var b=h.type,e=h.target,f;this.target=e&&a.nodeType(3,e)?e.parentNode:e;(e=l[b])||(l[b]=e=x.test(b)?
a.eventHooks.mouse:t.test(b)?a.eventHooks.keys:function(){return g});e=e(h,this,b);for(b=e.length;b--;)!((f=e[b])in this)&&f in h&&(this[f]=h[f])}}var c=window,e=document||{},k=e.documentElement||{},p=a.isString,w=a.isFunction,r={},u=/\s*,\s*|\s+/,t=/^key/,x=/^(?:mouse|pointer|contextmenu)|click/,v=/[^\.]*(?=\..*)\.|.*/,y=/\..*/,l={},f=Array.prototype.slice,b={disabeled:function(a,b){if(a.disabeled&&"click"===b)return!0},nodeType:function(h){if(a.nodeType(3,h)||a.nodeType(8,h))return!0}},B={pointerenter:{fix:"pointerover",
condition:n},pointerleave:{fix:"pointerout",condition:n},mouseenter:{fix:"mouseover",condition:s},mouseleave:{fix:"mouseout",condition:s},mousewheel:{fix:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},g="altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" ");d.prototype={preventDefault:function(){this.originalEvent.preventDefault?this.originalEvent.preventDefault():this.originalEvent.returnValue=!1},stopPropagation:function(){this.originalEvent.stopPropagation?
this.originalEvent.stopPropagation():this.originalEvent.cancelBubble=!0},stop:function(){this.preventDefault();this.stopPropagation();this.stopped=!0},stopImmediatePropagation:function(){this.originalEvent.stopImmediatePropagation&&this.originalEvent.stopImmediatePropagation();this.isImmediatePropagationStopped=function(){return!0}},isImmediatePropagationStopped:function(){return this.originalEvent.isImmediatePropagationStopped&&this.originalEvent.isImmediatePropagationStopped()},clone:function(a){var b=
d(this,this.element);b.currentTarget=a;return b}};a.Events={add:function(h,m,c,g,e){var l,d,k,p,n,s;if(b.disabeled(h,m)||b.nodeType(h))return!1;if(void 0===c&&"object"===typeof m)for(l in m)m.hasOwnProperty(l)&&a.Events.add.call(this,h,l,m[l]);else{w(c)?(p=f.call(arguments,3),g=l=c):(l=g,p=f.call(arguments,4),g=a.Events.delegate(c,l));d=m.split(u);1===e&&(g=a.Events.once(a.Events.remove,h,m,g,l));for(k=d.length;k--;)(s=a.Events.putHandler(n=a.Kernel(h,d[k].replace(y,""),g,l,d[k].replace(v,"").split("."),
p,!1)))&&h.addEventListener(n.eventType,a.Events.rootListener,!1);return h}},remove:function(h,b,c){var g=p(b),e;if(g&&0<b.indexOf(" ")){b=b.split(b);for(e=b.length;e--;)a.Events.remove(h,b[e],c);return h}(e=g&&b.replace(y,""))&&B[e]&&(e=B[e].fix);if(!b||g){if(b=g&&b.replace(v,""))b=b.split(".");a.Events.removeListener(h,e,c,b)}else if(w(b))a.Events.removeListener(h,null,b);else for(var f in b)b.hasOwnProperty(f)&&a.Events.remove(h,f,b[f]);return h},delegate:function(h,b){function c(b,m){for(var g,
q=p(h)?a.select(h,m):h;b&&b!==m;b=b.parentNode)if(null!==q)for(g=q.length;g--;)if(q[g]===b)return b}function g(a){if(!0!==a.target.disabled){var h=c(a.target,this);h&&b.apply(h,arguments)}}g.__handlers={ft:c,selector:h};return g},removeListener:function(h,b,c,g){b=b&&b.replace(y,"");b=a.Events.getHandler(h,b,null,!1);var e={},f,l;f=0;for(l=b.length;f<l;f++)c&&b[f].original!==c||!b[f].inNamespaces(g)||(a.Events.delHandler(b[f]),e[b[f].eventType]||(e[b[f].eventType]={t:b[f].eventType,c:b[f].type}));
for(f in e)a.Events.hasHandler(h,e[f].t,null,!1)||h.removeEventListener(e[f].t,a.Events.rootListener,!1)},once:function(a,b,c,g,e){return function(){g.apply(this,arguments);a(b,c,e)}},rootListener:function(b,c){var g=a.Events.getHandler(this,c||b.type,null,!1),e=g.length,f=0;b=d(b,this,!0);c&&(b.type=c);for(;f<e&&!b.isImmediatePropagationStopped();f++)g[f].removed||g[f].handler.call(this,b)},wrappedHandler:function(a,b,c,g){function e(c,q){return b.apply(a,g?f.call(q).concat(g):q)}var l=c?function(g){var f=
b.__handlers?b.__handlers.ft(g.target,a):this;if(c.apply(f,arguments))return g&&(g.currentTarget=f),e(g,arguments)}:function(c){b.__handlers&&(c=c.clone(b.__handlers?b.__handlers.ft(c.target,a):void 0));return e(c,arguments)};l.__handlers=b.__handlers;return l},findIt:function(b,c,g,e,f,l){if(c&&"*"!==c){var d=0,k=r[f?"r":"#"+c];if(k)for(f=k.length;d<f&&("*"!==b&&!k[d].matches(b,g,e)||l(k[d],k,d,c));d++);}else for(d in r)(d.charAt(0)===f||1)&&a.Events.findIt(b,d.substr(1),g,e,f,l)},hasHandler:function(a,
b,c,g){if(g=r[(g?"r":"#")+b])for(b=g.length;b--;)if(!g[b].root&&g[b].matches(a,c,null))return!0;return!1},getHandler:function(b,c,g,e){var f=[];a.Events.findIt(b,c,g,null,e,function(a){f.push(a)});return f},putHandler:function(a){var b=!a.root&&!this.hasHandler(a.element,a.type,null,!1),c=(a.root?"r":"#")+a.type;(r[c]||(r[c]=[])).push(a);return b},delHandler:function(b){a.Events.findIt(b.element,b.type,null,b.handler,b.root,function(a,b,c){b.splice(c,1);a.removed=!0;0===b.length&&delete r[(a.root?
"r":"#")+a.type];return!1})}};a.extend(a,{eventHooks:{keys:function(a,b){b.keyCode=a.keyCode||a.which;return g.concat(["char","charCode","key","keyCode"])},mouse:function(a,b){b.rightClick=3===a.which||2===a.button;b.pos={x:0,y:0};if(a.pageX||a.pageY)b.clientX=a.pageX,b.clientY=a.pageY;else if(a.clientX||a.clientY)b.clientX=a.clientX+e.body.scrollLeft+k.scrollLeft,b.clientY=a.clientY+e.body.scrollTop+k.scrollTop;return g.concat("button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "))}},
Kernel:function(b,c,g,e,f,l){if(!(this instanceof a.Kernel))return new a.Kernel(b,c,g,e,f,l);var d=B[c];"unload"===c&&(g=a.Events.once(a.Events.removeListener,b,c,g,e));d&&(d.condition&&(g=a.Events.wrappedHandler(b,g,d.condition,l)),c=d.fix||c);this.element=b;this.type=c;this.original=e;this.namespaces=f;this.eventType=c;this.target=b;this.handler=a.Events.wrappedHandler(b,g,null,l)}});a.Kernel.prototype.inNamespaces=function(a){var b,c,g=0;if(!a)return!0;if(!this.namespaces)return!1;for(b=a.length;b--;)for(c=
this.namespaces.length;c--;)a[b]==this.namespaces[c]&&g++;return a.length===g};a.Kernel.prototype.matches=function(a,b,c){return this.element===a&&(!b||this.original===b)&&(!c||this.handler===c)};a.extend(a.fn,{on:function(b,c,g,e){return this.each(function(){a.Events.add(this,b,c,g,e)})},one:function(a,b,c){return this.on(a,b,c,1)},off:function(b,c){return this.each(function(){a.Events.remove(this,b,c)})},trigger:function(g,m){var f=this[0],l=g.split(u),k,p,n,s,r,t;if(b.disabeled(f,g)||b.nodeType(f))return!1;
for(k=l.length;k--;){g=l[k].replace(r,"");if(r=l[k].replace(v,""))r=r.split(".");if(r||m)for(t=a.Events.getHandler(f,g,null,!1),p=d(null,f),p.type=g,s=m?"apply":"call",m=m?[p].concat(m):p,p=0,n=t.length;p<n;p++){if(t[p].inNamespaces(r))t[p].handler[s](f,m)}else s=e.createEvent("HTMLEvents"),s.initEvent(g,!0,!0,c,1),f.dispatchEvent(s)}return f}});a.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(b,c){a.fn[c]=function(a,b){return 0<arguments.length?this.on(c,a,b):this.trigger(c)}})})(hAzzle);
(function(a){function s(e,d,p){if(!a.nodeType(1,e)||a.nodeType(9,e)||!+e.nodeType)return 0;e=a.getUID(e);(c[e]||(c[e]={}))[d]=p}function n(e,d){var p=c[a.getUID(e)];if(p)return 1===arguments.length?p:p[d]}function d(e,d){var p=a.getUID(e);void 0===d&&a.nodeType(1,e)?c[p]={}:c[p]?delete c[p].key:c[p]=null}var c={};a.extend({hasData:function(e,d){if(e.nodeType)return c[a.getUID(e)]?!0:!1},removeData:function(c,k){if(c instanceof a){if(d(c,k))return!0}else if(d(a(c),k))return!0;return!1},data:function(a,
c,d){if("undefined"===typeof d)return n(a,c);s(a,c,d)}});a.extend(a.fn,{removeData:function(a){return this.each(function(){d(this,a)})},data:function(a,c){var d=arguments.length;return 1===d?1===this.elems.length?n(this.elems[0],a):this.elems.map(function(c){return n(c,a)}):2===d?this.each(function(){s(this,a,c)}):n(this[0])}})})(hAzzle);
(function(a){function s(c,e){var b,d,g=e||!1,h=[],m=encodeURIComponent,q=function(b,c){c=a.isFunction(c)?c():null===c?"":c;h[h.length]=m(b)+"="+m(c)};if(a.isArray(c))for(d=0;c&&d<c.length;d++)q(c[d].name,c[d].value);else for(d=0;b=nativeKeys(c)[d];d+=1)n(b,c[b],g,q,c);return h.join("&").replace(/%20/g,"+")}function n(c,e,b,d,g){var h,m=/\[\]$/;if(a.isArray(e))for(g=0;e&&g<e.length;g++)h=e[g],b||m.test(c)?d(c,h):n(c+"["+(a.isObject(h)?g:"")+"]",h,b,d);else if(e&&"[object Object]"===e.toString())for(h in e)g[w](c)&&
n(c+"["+h+"]",e[h],b,d);else d(c,e)}function d(a){t=a}function c(c,f,b){var n=u++,g=c.jsonpCallback||"callback";c=c.jsonpCallbackName||"hAzzel_"+v();var h=RegExp("((^|\\?|&)"+g+")=([^&]+)"),m=b.match(h),q=k[p]("script"),z=0;m?"?"===m[3]?b=b.replace(h,"$1="+c):c=m[3]:b=(b+"&"+(g+"="+c)).replace(/[&?]+/,"?");e[c]=d;q.type="text/javascript";q.src=b;q.async=!0;a.isDefined(q.onreadystatechange)&&!x&&(q.event="onclick",q.htmlFor=q.id="_hAzzel_"+n);q.onload=q.onreadystatechange=function(){if(q.readyState&&
"complete"!==q.readyState&&"loaded"!==q.readyState||z)return!1;q.onload=q.onreadystatechange=null;if(q.onclick)q.onclick();f(t);t=void 0;r.removeChild(q);z=1};r.appendChild(q);return{abort:function(){q.onload=q.onreadystatechange=null;t=void 0;r.removeChild(q);z=1}}}var e=window,k=document,p="createElement",w="hasOwnProperty",r=k.head||k.getElementsByTagName("head")[0],u=0,t,x=-1!==a.indexOf(navigator.userAgent,"MSIE 10.0"),u=0,v=Date.now||function(){return(new Date).getTime()},y={"*":"*/".concat("*"),
text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript",js:"application/javascript, text/javascript"};a.extend({ajax:function(d,f){d=d||{};f=f||function(){};var b,k=d.headers||{},g=nativeKeys(k),h=-1,m=g.length,q=(d.method||"GET").toLowerCase(),z=a.isString(d)?d:d.url,p=d.type?d.type.toLowerCase():"",n=null,r=!1!==(d.processData||!0)&&d.data&&!a.isString(d.data)?s(d.data):d.data||null,t=!1;if(!z)return!1;"jsonp"!==p&&"get"!==q.toLowerCase()||!r||
(z=(z+"&"+r).replace(/[&?]+/,"?"),r=null);if("jsonp"===p&&/(=)\?(?=&|$)|\?\?/.test(z))return c(d,f,z);if(!0===d.crossOrigin){var w=e.XMLHttpRequest?new XMLHttpRequest:null;if(w&&"withCredentials"in w)b=w;else if(e.xDomainRequest)b=new "XDomainRequest";else throw"Browser does not support cross-origin requests";}b.open(q,z,!1===d.async?!1:!0);k.Accept=k.Accept||y[p]||y["*"];d.crossOrigin||k.requestedWith||(k.requestedWith="XMLHttpRequest");for((d.contentType||d.data&&"get"!==p.toLowerCase())&&b.setRequestHeader("Content-Type",
d.contentType||"application/x-www-form-urlencoded");++h<m;)b.setRequestHeader(a.trim(g[h]),k[g[h]]);a.isDefined(d.withCredentials)&&a.isDefined(b.withCredentials)&&(b.withCredentials=!!d.withCredentials);0<d.timeout&&(n=setTimeout(function(){b.abort()},d.timeout));e.XDomainRequest&&b instanceof e.xDomainRequest?(b.onload=f,b.onerror=err,b.onprogress=function(){},t=!0):b.onreadystatechange=function(){if(4===b.readyState)if(200<=b.status&&300>b.status||304===b.status){var a;b&&("json"===p&&null===(a=
JSON.parse(b.responseText))&&(a=b.responseText),a="xml"===p?b.responseXML&&b.responseXML.parseError&&b.responseXML.parseError.errorCode&&b.responseXML.parseError.reason?null:b.responseXML:a||b.responseText);!a&&r&&(a=r);d.success&&d.success(a)}else void 0!==d.error&&(null!==n&&clearTimeout(n),d.error("error",d,b))};d.before&&d.before(b);t?setTimeout(function(){b.send(r)},200):b.send(r);return b},getJSON:function(c,e,b,d){a.ajax({url:c,method:"JSON",contentType:"application/json",error:a.isFunction(d)?
d:function(a){},data:a.isObject(e)?e:{},success:a.isFunction?b:function(a){}})},get:function(c,e,b,d){a.ajax({url:c,method:"GET",contentType:"",error:a.isFunction(d)?d:function(a){},data:a.isObject(e)?e:{},success:a.isFunction?b:function(a){}})},post:function(c,e,b,d){a.ajax({url:c,method:"POST",contentType:"",error:a.isFunction(d)?d:function(a){},data:a.isObject(e)?e:{},success:a.isFunction?b:function(a){}})}})})(hAzzle);
(function(a){var s=hAzzle.support.classList,n=/\S+/g,d=/[\t\r\n\f]/g;a.extend(a.fn,{addClass:function(a){if("function"===typeof a)return this.each(function(e){hAzzle(this).addClass(a.call(this,e,this.className))});var e,k,p,w,r=(a||"").match(n)||[];return this.each(function(a,c){if(s&&hAzzle.nodeType(1,c))return hAzzle.each(r,function(a,e){return c.classList.add(e)});if(e=hAzzle.nodeType(1,c)&&(c.className?(" "+c.className+" ").replace(d," "):" ")){for(k=0;p=r[k++];)0>e.indexOf(" "+p+" ")&&(e+=p+
" ");w=hAzzle.trim(e);c.className!==w&&(c.className=w)}})},removeClass:function(a){var e,k,p,w,r;if(hAzzle.isFunction(a))return this.each(function(e){hAzzle(this).removeClass(a.call(this,e,this.className))});e=(a||"").match(n)||[];return this.each(function(n,t){if(!a)return t.className="";if(s&&hAzzle.nodeType(1,t))return hAzzle.each(e,function(a,c){t.classList.remove(c)});if(k=hAzzle.nodeType(1,t)&&(t.className?(" "+t.className+" ").replace(d," "):"")){for(w=0;p=e[w++];)for(;0<=k.indexOf(" "+p+" ");)k=
k.replace(" "+p+" "," ");r=a?hAzzle.trim(k):"";t.className!==r&&(t.className=r)}})},hasClass:function(a){for(var e=" "+a+" ",k=0,p=this.length;k<p;k++){if(s&&hAzzle.nodeType(1,this[k]))return this[k].classList.contains(a);if(hAzzle.nodeType(1,this[k])&&0<=(" "+this[k].className+" ").replace(d," ").indexOf(e))return!0}return!1},replaceClass:function(a,e){var d,p;return this.each(function(){d=this.className.split(" ");p=!1;for(var n=d.length;n--;)d[n]==a&&(p=!0,d[n]=e);if(!p)return hAzzle(this).addClass(e,
this);this.className=d.join(" ")})},tempClass:function(a,e){return this.each(function(d,p){hAzzle(p).addClass(a);setTimeout(function(){hAzzle(p).removeClass(a)},e||100)})},allClass:function(){return s?this[0].classList:this},toggleClass:function(a,e){var d=typeof a;return"boolean"===typeof e&&"string"===d?e?this.addClass(a):this.removeClass(a):hAzzle.isFunction(a)?this.each(function(d){hAzzle(this).toggleClass(a.call(this,d,this.className,e),e)}):this.each(function(e,w){if(s)return this.classList.toggle(a);
if("string"===typeof a)for(var r,u=0,t=hAzzle(this),x=a.match(n)||[];r=x[u++];)t.hasClass(r)?t.removeClass(r):t.addClass(r);else if("undefined"===d||"boolean"===d)this.className&&hAzzle.data(this,"__className__",this.className),this.className=this.className||!1===a?"":hAzzle.data(this,"__className__")||""})}})})(hAzzle);
(function(a){function s(b,c){if(c in b)return c;var e=c;c=a.prefix(c);return c in b?c:e}function n(a,b){return"none"===(b||a).style.display}function d(b){var c=b.style;"none"===c.display&&(c.display="");(""===c.display&&"none"===p(b,"display")||!a.contains(b.ownerDocument.documentElement,b))&&a.data(b,"display",e(b.nodeName))}function c(b,c){var e,d=a(c.createElement(b)).appendTo(c.body),f=window.getDefaultComputedStyle&&(e=window.getDefaultComputedStyle(d[0]))?e.display:a.css(d[0],"display");d.detach();
return f}function e(b){var h=document,e=B[b];if(!e){e=c(b,h);if("none"===e||!e){var d=(d||a("<iframe frameborder='0' width='0' height='0'/>")).appendTo(h.documentElement),h=d[0].contentDocument;h.write();h.close();e=c(b,h);d.detach()}B[b]=e}return e}function k(b){if(!n(b)){var c=a.css(b,"display");"none"!==c&&a.data(b,"display",c);a.style(b,"display","none")}}function p(b,c,e,d){var f,k;d||(d=b.style);if(e=e||b.ownerDocument.defaultView.getComputedStyle(b,null))k=e.getPropertyValue(c)||e[c],""!==
k||a.contains(b.ownerDocument,b)||(k=a.style(b,c)),l.test(c)&&v.test(k)&&(b=d.width,c=d.minWidth,f=d.maxWidth,d.minWidth=d.maxWidth=d.width=k,k=e.width,d.width=b,d.minWidth=c,d.maxWidth=f);return void 0!==k?k+"":k}function w(b,c,e){var d="width"===c?b.offsetWidth:b.offsetHeight,f=!0,k=a.support.boxSizing&&"border-box"===a.css(b,"boxSizing");if(0>=d){d=p(b,c);if(0>d||null===d)d=b.style[c];if(y.test(d))return d;f=k&&(a.support.boxSizingReliable||d===b.style[c]);d=parseFloat(d)||0}return d+r(b,c,e||
(k?"border":"content"),f)+"px"}function r(c,d,e,f){d=e===(f?"border":"content")?4:"width"===d?1:0;for(var k=0;4>d;d+=2)"margin"===e&&(k+=a.css(c,e+b[d],!0)),f?("content"===e&&(k-=parseFloat(p(c,"padding"+b[d]))||0),"margin"!==e&&(k-=parseFloat(p(c,"border"+b[d]+"Width"))||0)):(k+=parseFloat(p(c,"padding"+b[d]))||0,"padding"!==e&&(k+=parseFloat(p(c,"border"+b[d]+"Width"))||0));return k}var u=window.document.documentElement,t=/\s+(!important)/g,x=/background/i,v=/^([+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|))(?!px)[a-z%]+$/i,
y=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,l=/^margin/,f=/^([+-])=([+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|))(.*)/i,b=["Top","Right","Bottom","Left"],B={};a.extend({cssNumber:{"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},cssHooks:{opacity:{get:function(a,b){if(b){var c=p(a,"opacity");return""===c?"1":c}}}},cssNormalTransform:{letterSpacing:"0",fontWeight:"400"},cssProps:{"float":"cssFloat"},pixelsToUnity:function(b,c,d,e){if(""===c||"px"===c)return b;if("em"===c)return b/
hAzzle.css(d,"fontSize","");if("%"===c){/^(left$|right$|margin|padding)/.test(e)?e="width":/^(top|bottom)$/.test(e)&&(e="height");if(d=/^(relative|absolute|fixed)$/.test(a.css(d,"position"))?d.offsetParent:d.parentNode)if(e=a.css(d,e,!0),0!==e)return b/e*100;return 0}void 0===a.pixelsToUnity.units&&(d=a.pixelsToUnity.units={},e=document.createElement("div"),e.style.width="100cm",document.body.appendChild(e),d.mm=e.offsetWidth/1E3,document.body.removeChild(e),d.cm=10*d.mm,d.inn=2.54*d.cm,d.pt=1*d.inn/
72,d.pc=12*d.pt);return(c=a.pixelsToUnity.units[c])?b/c:b},css:function(b,c,d,e,f){var k,l=b.style;f||(c=a.camelCase(c),c=a.cssProps[c]||(a.cssProps[c]=s(l,c)));(f=a.cssHooks[c])&&(k=f.get(b,!0,d));void 0===k&&(k=p(b,c,e,l));"normal"===k&&c in a.cssNormalTransform&&(k=a.cssNormalTransform[c]);return""===d||d?(b=parseFloat(k),!0===d||a.isNumeric(b)?b||0:k):k},style:function(b,c,d,e,k){if(b&&!a.nodeType(3,b)&&!a.nodeType(8,b)){k=b.style;var l,p=!1;if(k&&(c=a.cssProps[c]||(a.cssProps[c]=s(k,c)),c=e?
c.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase():a.camelCase(c),"string"===typeof d&&(l=f.exec(d))&&(d=a.css(b,c,"","",c),d=a.pixelsToUnity(d,l[3],b,c)+(l[1]+1)*l[2],p=!0),null!==d&&d===d)){p&&!a.cssNumber[c]&&(d+=l&&l[3]?l[3]:"px");if(""===d&&x.test(c)){if(e)return c+":inherit";k[c]="inherit"}if(e)return c+":"+d;k[c]=d}}},setOffset:function(b,c,d){var e,f,k,l=a.css(b,"position"),p=a(b),n={};"static"===l&&(b.style.position=
"relative");k=p.offset();f=a.css(b,"top");e=a.css(b,"left");("absolute"===l||"fixed"===l)&&-1<(f+e).indexOf("auto")?(e=p.position(),f=e.top,e=e.left):(f=parseFloat(f)||0,e=parseFloat(e)||0);a.isFunction(c)&&(c=c.call(b,d,k));null!==c.top&&(n.top=c.top-k.top+f);null!==c.left&&(n.left=c.left-k.left+e);"using"in c?c.using.call(b,n):p.css(n)}});a.extend(a.fn,{show:function(){return this.each(function(){d(this)})},hide:function(){return this.each(function(){k(this)})},toggle:function(a){return"boolean"===
typeof a?a?this.show():this.hide():this.each(function(){n(this)?d(this):k(this)})},css:function(b,c){if(1===arguments.length){if("string"===typeof b)return this[0]&&a.css(this[0],b);for(var d in b)this.each(function(){t.test(b[d])?this.style.cssText+=a.style(this,d,b[d],!0):a.style(this,d,b[d])})}else return this.each(function(){t.test(c)?this.style.cssText+=a.style(this,b,c,!0):a.style(this,b,c)})},setOpacity:function(b){if(a.isNumber)return this.each(function(){this.style.opacity=b/100})},offset:function(b){if(arguments.length)return void 0===
b?this:this.each(function(c){a.setOffset(this,b,c)});var c=this[0],d,e=u.clientTop,f=u.clientLeft,k=c&&c.ownerDocument;if(k){d=a.isWindow(k)?k:a.nodeType(9,k)&&k.defaultView;k=d.pageYOffset||u.scrollTop;d=d.pageXOffset||u.scrollLeft;var l={top:0,left:0};if(c&&c.ownerDocument){if(!a.contains(u,c))return l;"undefined"!==typeof c.getBoundingClientRect&&(l=c.getBoundingClientRect());return{top:l.top+k-e,left:l.left+d-f,right:l.right+d-f,bottom:l.bottom+k-e,width:l.right-l.left,height:l.bottom-l.top}}}},
position:function(){if(this.length){var b,c,d=this[0],e={top:0,left:0};"fixed"===a.css(d,"position")?c=d.getBoundingClientRect():(b=this.offsetParent(),c=this.offset(),a.nodeName(b[0],"html")||(e=b.offset()),e.top+=a.css(b[0],"borderTopWidth",!0),e.left+=a.css(b[0],"borderLeftWidth",!0));return{top:c.top-e.top-a.css(d,"marginTop",!0),left:c.left-e.left-a.css(d,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(b){for(b=b.offsetParent||u;b&&!a.nodeName(b,"html")&&"static"===a.css(b,
"position");)b=b.offsetParent;return b||u})}});a.each(["Height","Width"],function(b,c){var d=c.toLowerCase();a.fn["inner"+c]=function(){var b=this[0];return b?b.style?parseFloat(a.css(b,d,"padding")):this[d]():null};a.fn["outer"+c]=function(b){var c=this[0];return c?c.style?parseFloat(a.css(c,d,b?"margin":"border")):this[d]():null};a.fn[d]=function(b){var e=this[0],f;if(!e)return null===b?null:this;if(a.isFunction(b))return this.each(function(c){var e=a(this);e[d](b.call(this,c,e[d]()))});if(a.isWindow(e))return e.document.documentElement["client"+
c];if(a.nodeType(9,e))return f=e.documentElement,Math.max(e.body["scroll"+c],f["scroll"+c],e.body["offset"+c],f["offset"+c],f["client"+c]);if(void 0===b)return parseFloat(a.css(e,d));a.style(e,d,b);return this}});a.each(["height","width"],function(b,c){a.cssHooks[c]={displaySwap:/^(none|table(?!-c[ea]).+)/,numsplit:/^([\-+]?(?:\d*\.)?\d+)(.*)$/i,cssShow:{position:"absolute",visibility:"hidden",display:"block"},get:function(a,b,c){if(b){if(0===a.offsetWidth&&this.displaySwap.test(hAzzle.css(a,"display"))){var d;
c={};for(d in this.cssShow)c[d]=a.style[d],a.style[d]=this.cssShow[d];b=w(a);for(d in this.cssShow)a.style[d]=c[d];return b}w(a,d,c)}},setPositiveNumber:function(a,b){var c=this.numsplit.exec(a);return c?Math.max(0,c[1]-(b||0))+(c[2]||"px"):a},set:function(a,b,d){alert("dd");var e=d&&a.ownerDocument.defaultView.getComputedStyle(a,null);return this.setPositiveNumber(b,d?r(a,c,d,"border-box"===hAzzle.css(a,"boxSizing",!1,e),e):0)}}});a.each({scrollTop:"pageYOffset",scrollLeft:"pageXOffset"},function(b,
c){a.fn[b]=function(d){var e=this[0],f=a.isWindow(e)?e:a.nodeType(9,e)&&e.defaultView;if("undefined"===typeof d)return d?d[c]:e[b];f?f.scrollTo(window[b]):e[b]=d}});a.each(["margin","padding"],function(c,d){a.cssHooks[d]={get:function(c,e,f){return a.map(b,function(b){return a.css(c,d+b)}).join(" ")},set:function(c,e){var f=e.split(/\s/),g={Top:f[0],Right:f[1]||f[0],Bottom:f[2]||f[0],Left:f[3]||f[1]||f[0]};a.each(b,function(a,b){c.style[d+b]=g[b]})}}})})(hAzzle);
(function(a){var s;a.extend(a.fn,{empty:function(){return this.removeData().each(function(n,d){a.nodeType(1,this)&&(a.each(d,function(c,d){a.Events.remove(d)}),this.textContent="")})},remove:function(){return this.removeData().each(function(n,d){var c=a(d).find("*"),c=c.add(d);a.each(c,function(){a.Events.remove(d)});d.parentNode&&("IMG"===d.tagName&&(cache.push(d),d.src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=",s&&clearTimeout(s),s=setTimeout(function(){cache=[]},6E4)),this.parentNode.removeChild(d))})}})})(hAzzle);
(function(a){a.extend(a,{parseJSON:function(a){return hAzzle.isString(a)?JSON.parse(a+""):a},parseXML:function(a){var n,d;if(!a||"string"!==typeof a)return null;try{d=new DOMParser,n=d.parseFromString(a,"text/xml")}catch(c){n=void 0}return!n||n.getElementsByTagName("parsererror").length?Error("Invalid XML: "+a):n}})})(hAzzle);
(function(a){var s=a.isObject,n=a.isString,d=document;(function(){var a=!1;try{localStorage.setItem("hAzzle","hAzzle"),localStorage.removeItem("hAzzle"),a=!0}catch(e){a=!1}a||(window.localStorage={getItem:function(a){return a&&this.hasOwnProperty(a)?unescape(d.cookie.replace(RegExp("(?:^|.*;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*((?:[^;](?!;))*[^;]?).*"),"$1")):null},key:function(a){return unescape(d.cookie.replace(/\s*\=(?:.(?!;))*$/,"").split(/\s*\=(?:[^;](?!;))*[^;]?;\s*/)[a])},
setItem:function(a,c){a&&(d.cookie=escape(a)+"="+escape(c)+"; expires=Tue, 19 Jan 2038 03:14:07 GMT; path=/",this.length=d.cookie.match(/\=/g).length)},length:0,removeItem:function(a){a&&this.hasOwnProperty(a)&&(d.cookie=escape(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/",this.length--)},hasOwnProperty:function(a){return RegExp("(?:^|;\\s*)"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=").test(d.cookie)}},window.localStorage.length=(d.cookie.match(/\=/g)||window.localStorage).length)})();
a.extend({bytesToSize:function(a){if(0===a)return"0 Bytes";var d=parseInt(Math.floor(Math.log(a)/Math.log(1E3)),10);return(a/Math.pow(1E3,d)).toPrecision(3)+" "+["Bytes","KB","MB","GB","TB"][d]},clearStorage:function(){localStorage.clear()},storageContains:function(c){if(n(c))return-1!==a.indexOf(this.getStorageKeys(),c)},getStorageKeys:function(){for(var a=[],d=0,d=localStorage.length;d--;)a.push(localStorage.key(d));return a},getRemainingStorageSpace:function(){return this.bytesToSize(5242880-this.getStorageSize(!0))},
getStorageSize:function(a){return a?JSON.stringify(localStorage).length:this.bytesToSize(JSON.stringify(localStorage).length)},isStorageEmpty:function(){return 0===this.getStorageKeys().length},removeStorage:function(a){if(n(a))localStorage.removeItem(a);else if(a instanceof Array)for(var d=a.length;d--;)n(a[d])&&localStorage.removeItem(a[d])},getStorage:function(c,d){if(n(c)){var k=localStorage.getItem(c).toLowerCase(),p=parseFloat(k);if(null===k)return 2===arguments.length?d:null;if(!a.IsNaN(p))return p;
if("true"===k||"false"===k)return"true"===k;try{return k=a.parseJSON(k)}catch(s){return k}}},setStorage:function(a,d){1===arguments.length?this.store(a):n(a)&&(s(d)&&(d=JSON.stringify(d)),localStorage.setItem(a,d))},saveStorage:function(a){var d;if(s(a)&&!(a instanceof Array))for(d in a)localStorage.setItem(d,a[d])},StorageToObject:function(){for(var a={},d=this.getStorageKeys(),k=0,k=d.length;k--;)a[d[k]]=this.getStorage(d[k]);return a}})})(hAzzle);
(function(a){function s(a,c){var e=c.nodeName.toLowerCase();if("input"===e&&n.test(a.type))c.checked=a.checked;else if("input"===e||"textarea"===e)c.defaultValue=a.defaultValue}(function(){var a=document.createDocumentFragment().appendChild(document.createElement("div")),c=document.createElement("input");c.setAttribute("type","radio");c.setAttribute("checked","checked");c.setAttribute("name","t");a.appendChild(c);hAzzle.support.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML=
"<textarea>x</textarea>";hAzzle.support.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();var n=/^(?:checkbox|radio)$/i;a.extend(a.fn,{clone:function(d){var c,e,k,p;return this.map(function(n){var r=a.Events.getHandler(n,"",null,!1),u=r.length,t=0,x,v;e=a(n).data();for(c=n.cloneNode(d||!0);t<u;t++)r[t].original&&(x=[c,r[t].type],(v=r[t].handler.__handler)&&x.push(v.selector),x.push(r[t].original),a.Events.add.apply(null,x));e&&a.each(e,function(d,e){a.data(c,d,e)});if(!a.support.noCloneChecked&&
(a.nodeType(1,n)||a.nodeType(11,n))&&!a.isXML(n))for(p=a.getChildren(c),k=a.getChildren(n),t=0,u=k.length;t<u;t++)s(k[t],p[t]);p=a.getChildren(c,"script");0<p.length&&a.Evaluated(p,!a.contains(n.ownerDocument,n)&&a.getChildren(n,"script"));return c})}})})(hAzzle);