/*!
 * hAzzle.js
 * Copyright (c) 2014 Kenny Flashlight
 * Version: 0.2.9 - BETA 2
 * Released under the MIT License.
 *
 * Date: 2014-04-10
 *
 */
(function(s,m){function ya(a){return a?"string"===typeof a?c.select(a)[0]:!a[$]&&"object"===typeof a&&isFinite(a.length)?a[0]:a:q}function K(){if(!L){L=!0;for(var a=0;a<y.length;a++)y[a].fn.call(s,y[a].ctx);y=[]}}function z(a,b){var d=t[c.getUID(a)];return 1===arguments.length?d:d[b]}function aa(a,b){var d=t[c.getUID(a)];if(null===b)return!1;if(d&&d[b])return!0}function M(a,b){var d=c.getUID(a);b===m&&c.nodeType(1,a)?t[d]={}:(d=t[d])&&delete d[b]}function ba(a){if(a=a.relatedTarget){var b;if(b=a!==
this)if(b="xul"!==a.prefix)if(b=!/document/.test(this.toString())){a:{for(;a=a.parentNode;)if(a===this){a=1;break a}a=0}b=!a}a=b}else a=null===a;return a}function ca(a){return a}function u(a,b){if(!(this instanceof u))return new u(a,b);if(arguments.length&&(this.originalEvent=a=a||((b.ownerDocument||b.document||b).parentWindow||win).evt)){var d=a.type,e=a.target,f;this.target=e&&c.nodeType(3,e)?e.parentNode:e;(e=da[d])||(da[d]=e=za.test(d)?c.eventHooks.mouse:Aa.test(d)?c.eventHooks.keys:function(){return N});
e=e(a,this,d);for(d=e.length;d--;)!((f=e[d])in this)&&f in a&&(this[f]=a[f])}}function ea(a){return c.nodeType(1,a)||c.nodeType(9,a)||c.nodeType(11,a)?!0:!1}function v(a,b,d){if(a)return c.isWindow(a)?a.document.documentElement.clientHeight:c.nodeType(9,a)?(d=a.documentElement,Math.max(a.body["scroll"+b],d["scroll"+b],a.body["offset"+b],d["offset"+b],d["client"+b])):c.css(a,b,d)}function fa(a){return c.isWindow(a)?a:c.nodeType(9,a)&&a.defaultView}function ga(a,b,d){var e=!0,f="width"===b?a.offsetWidth:
a.offsetHeight,g=a.ownerDocument.defaultView.getComputedStyle(a,null),k="border-box"===c.css(a,"boxSizing",!1,g);if(0>=f||null===f){f=O(a,b,g);if(0>f||null===f)f=a.style[b];if(ha.test(f))return f;e=k&&(c.support.boxSizingReliable()||f===a.style[b]);f=parseFloat(f)||0}return f+ia(a,b,d||(k?"border":"content"),e,g)+"px"}function ia(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+A[b],!0,f)),e?("content"===d&&(g-=c.css(a,"padding"+A[b],!0,f)),
"margin"!==d&&(g-=c.css(a,"border"+A[b]+"Width",!0,f))):(g+=c.css(a,"padding"+A[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+A[b]+"Width",!0,f)));return g}function P(a,b){return"none"===(b||a).style.display}function ja(a){if(P(a))return c.style(a,"display",c.data(a,"display")||"block")}function ka(a){if(!P(a)){var b=c.css(a,"display");"none"!==b&&c.data(a,"display",b);c.style(a,"display","none")}}function O(a,b,d){var e,f,g=a.style;(d=d||a.ownerDocument.defaultView.getComputedStyle(a,null))&&(f=d.getPropertyValue(b)||
d[b]);d&&(""!==f||c.contains(a.ownerDocument,a)||(f=c.style(a,b)),ha.test(f)&&Ba.test(b)&&(a=g.width,b=g.minWidth,e=g.maxWidth,g.minWidth=g.maxWidth=g.width=f,f=d.width,g.width=a,g.minWidth=b,g.maxWidth=e));return f!==m?f+"":f}function la(a,b){if(!n[a+b]){if(b in a)return b;for(var d=b[0].toUpperCase()+b.slice(1),c=b,f=ma.length;f--;)if(b=ma[f]+d,b in a)return b;n[a+b]=c}return n[a+b]}function Ca(a,b){var d,e,f=b||!1,g=[],k=encodeURIComponent,h=function(a,b){b=c.isFunction(b)?b():null===b?"":b;g[g.length]=
k(a)+"="+k(b)};if(c.isArray(a))for(e=0;a&&e<a.length;e++)h(a[e].name,a[e].value);else for(e=0;d=nativeKeys(a)[e];e+=1)R(d,a[d],f,h,a);return g.join("&").replace(/%20/g,"+")}function R(a,b,d,e,f){var g,k=/\[\]$/;if(c.isArray(b))for(f=0;b&&f<b.length;f++)g=b[f],d||k.test(a)?e(a,g):R(a+"["+(c.isObject(g)?f:"")+"]",g,d,e);else if(b&&"[object Object]"===b.toString())for(g in b)f[na](a)&&R(a+"["+g+"]",b[g],d,e);else e(a,b)}function Da(a){D=a}function Ea(a,b,d){var e=oa++,f=a.jsonpCallback||"callback";a=
a.jsonpCallbackName||"hAzzel_"+S();var g=RegExp("((^|\\?|&)"+f+")=([^&]+)"),k=d.match(g),h=q[Fa]("script"),l=0;k?"?"===k[3]?d=d.replace(g,"$1="+a):a=k[3]:d=(d+"&"+(f+"="+a)).replace(/[&?]+/,"?");win[a]=Da;h.type="text/javascript";h.src=d;h.async=!0;c.isDefined(h.onreadystatechange)&&!Ga&&(h.event="onclick",h.htmlFor=h.id="_hAzzel_"+e);h.onload=h.onreadystatechange=function(){if(h.readyState&&"complete"!==h.readyState&&"loaded"!==h.readyState||l)return!1;h.onload=h.onreadystatechange=null;if(h.onclick)h.onclick();

b(D);D=m;T.removeChild(h);l=1};T.appendChild(h);return{abort:function(){h.onload=h.onreadystatechange=null;D=m;T.removeChild(h);l=1}}}function Ha(a,b){var d=b.nodeName.toLowerCase();if("input"===d&&Ia.test(a.type))b.checked=a.checked;else if("input"===d||"textarea"===d)b.defaultValue=a.defaultValue}function E(a,b){var d=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return b===m||b&&c.nodeName(a,b)?c.merge([a],d):d}function Ja(a,b){for(var d=
0,e=a.length;d<e;d++)c.data(a[d],"globalEval",!b||c.data(b[d],"globalEval"))}if(!s.hAzzle){var q=s.document,$="nodeType",q=document||{},Ka=q.documentElement,r=Array.prototype,F=Object.prototype,p=r.slice,La=r.splice,pa=r.concat,qa=F.toString,S=Date.now||function(){return(new Date).getTime()},Ma={current:0,next:function(){return++this.current}},n=[],U=[],w={1:function(a){if(1===a.nodeType)return!0},2:function(a){if(2===a.nodeType)return!0},3:function(a){if(3===a.nodeType)return!0},4:function(a){if(4===
a.nodeType)return!0},6:function(a){if(6===a.nodeType)return!0},8:function(a){if(8===a.nodeType)return!0},9:function(a){if(9===a.nodeType)return!0},11:function(a){if(11===a.nodeType)return!0}},B=q.createElement("div"),c=function(a,b){return new c.fn.init(a,b)},G=c.support={};(function(){G.classList=!!q.createElement("p").classList;var a=q.createElement("div");a.style&&(a.style.backgroundClip="content-box",a.cloneNode(!0).style.backgroundClip="",G.clearCloneStyle="content-box"===a.style.backgroundClip)})();
c.fn=c.prototype={length:0,init:function(a,b){var d,e;if(a instanceof c)return a;if(c.isString(a)){if("<"===a[0]&&">"===a[a.length-1]&&3<=a.length)return d=c.fragment(a.trim(),RegExp.$1,b),this.elems=d,this.length=1,this[0]=d,this;if(U[a]&&!b){this.elems=d=U[a];for(e=this.length=d.length;e--;)this[e]=d[e];return this}this.elems=U[a]=c.select(a,b)}else{if(c.isFunction(a)){if(c.ready)return c.ready(a);console.log("The DOM Ready module are not installed!!");return[]}if(a instanceof Array)this.elems=
c.unique(a.filter(c.isElement));else{if(c.isObject(a))return this.elems=[a],this.length=1,this[0]=a,this;c.isNodeList(a)?this.elems=p.call(a).filter(c.isElement):c.isElement(a)?this.elems=[a]:this.elems=[]}}d=this.elems;for(e=this.length=d.length;e--;)this[e]=d[e];return this},each:function(a,b){return c.each(this,a,b)},find:function(a){var b=typeof a;if("string"===b){if(1===this.length)b="string"!==b?a[0]:c(a,this.elems[0]);else if("object"==b)var d=this,b=c(a).filter(function(){var a=this;return d.elems.some.call(d,
function(b){return c.contains(b,a)})});else b=this.elems.reduce(function(b,d){return b.concat(c.select(a,d))},[]);return c.create(b)}return this},filter:function(a,b){if("function"===typeof a){var d=a;return c.create(this.elems.filter(function(a,c){return d.call(a,a,c)!==(b||!1)}))}a&&"!"===a[0]&&(a=a.substr(1),b=!0);return c.create(this.elems.filter(function(d){return c.matches(d,a)!==(b||!1)}))},contains:function(a){var b;return c.create(this.elems.reduce(function(d,e){b=c.select(a,e);return d.concat(b.length?
e:null)},[]))},not:function(a){return this.filter(a||[],!0)},is:function(a){return 0<this.length&&0<this.filter(a||[]).length},pluck:function(a,b){b&&c.isNumber(b);return c.pluck(this.elems,a)},put:function(a,b,d){return c.put(this.elems,a,b,d)},get:function(a){return null!==a?this.elems[0>a?this.elems.length+a:a]:this.elems},map:function(a){return c(this.elems.map(a))},sort:function(a){return c(this.elems.sort(a))},concat:function(){var a=p.call(arguments).map(function(a){return a instanceof c?a.elements:
a});return c(pa.apply(this.elems,a))},slice:function(a,b){return c(p.call(this.elems,a,b))},splice:function(a,b){return c(La.call(this.elems,a,b))},push:function(a){return c.isElement(a)?(this.elems.push(a),this.length=this.elems.length,this.length-1):-1},indexOf:function(a){return c.indexOf(this.elems,a)},reduce:function(a,b){return this.elems.reduce(a,b)},reduceRight:function(a,b){return this.elems.reduceRight(a,b)},iterate:function(a,b){return function(d,c,f,g){return this.each(function(){a.call(b,
this,d,c,f,g)})}},eq:function(a){return c(null===a?"":this.get(a))}};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{};"object"!==typeof a&&"function"!==typeof a&&(a={});1===arguments.length&&(a=this);for(var b=p.call(arguments),d,c=b.length;c--;){d=b[c];for(var f in d)a[f]!==d[f]&&(a[f]=d[f])}return a};c.extend({each:function(a,b){var d=0,c=a.length;if(a.length===+a.length)for(;d<c&&!1!==b.call(a[d],d,a[d++]););else for(name in a)if(!1===b.call(a[name],name,a[name]))break;
return a},type:function(a){return(a=qa.call(a).match(/\s(\w+)\]$/))&&a[1].toLowerCase()},is:function(a,b){return 0<=c.indexOf(a,c.type(b))},isElement:function(a){return a&&(w[1](a)||w[9](a))},isNodeList:function(a){return a&&c.is(["nodelist","htmlcollection","htmlformcontrolscollection"],a)},IsNaN:function(a){return!(0>=a)&&!(0<a)},isUndefined:function(a){return"undefined"===typeof a},isDefined:function(a){return"undefined"!==typeof a},isObject:function(a){return null!==a&&"object"==typeof a},isString:function(a){return"string"===
typeof a},isNumeric:function(a){return!this.IsNaN(parseFloat(a))&&isFinite(a)},isNumber:function(a){return"number"===typeof a},isEmptyObject:function(a){for(var b in a)return!1;return!0},isFunction:function(a){return"function"===typeof a},isArray:Array.isArray,isArrayLike:function(a){if(null===a||this.isWindow(a))return!1},likeArray:function(a){return"number"==typeof a.length},isWindow:function(a){if(a)return null!==a&&a===a.window},isDocument:function(a){return null!==a&&a.nodeType==a.DOCUMENT_NODE},
isPlainObject:function(a){return this.isObject(a)&&!this.isWindow(a)&&Object.getPrototypeOf(a)===F},isBoolean:function(a){return"boolean"===typeof a},unique:function(a){return a.filter(function(b,d){return c.indexOf(a,b)===d})},create:function(a,b){return c.isUndefined(b)?c(a):c(a).filter(b)},prefix:function(a,b){var d,c=a[0].toUpperCase()+a.slice(1),f,g=["moz","webkit","ms","o"];b=b||s;if(d=b[a])return d;for(;(f=g.shift())&&!(d=b[f+c]););return d},matches:function(a,b){var d,e,f=function(a,b){b.parentNode||
B.appendChild(b);e=0<=c.indexOf(c.select(a,b.parentNode),b);b.parentNode===B&&B.removeChild(b);return e};return a&&c.isElement(a)&&b?b.nodeType?a===b:b instanceof c?b.elems.some(function(b){return c.matches(a,b)}):a===q?!1:(d=n[d]?n[d]:n[d]=c.prefix("matchesSelector",B))&&(n[b]?n[b]:n[b]=d.call(B,"div"))?d.call(a,b):f(b,a):!1},pluck:function(a,b){return a.map(function(a){return a[b]})},contains:function(a,b){if(Ka.compareDocumentPosition){var d=w[9](a)?a.documentElement:a,c=b&&b.parentNode;return a===
c||!!(c&&w[1](c)&&(d.contains?d.contains(c):a.compareDocumentPosition&&a.compareDocumentPosition(c)&16))}if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},indexOf:function(a,b){for(var d=0,c;c=a[d];d+=1)if(b===c)return d;return!1},now:S,nodeType:function(a,b){return w[a]?w[a](b):!1},trim:function(a){return a.trim()},noop:function(){},inArray:function(a,b){return c.inArray(a,b)},getUID:function(a){if(c.isDefined(a))return a.hAzzle_id||(a.hAzzle_id=Ma.next())},put:function(a,b,d,e){return c.each(a,
function(f){c.isDefined(e)&&null!==a&&c.nodeType(e,a);a[f][b]=d})},merge:function(a,b){for(var d=+b.length,c=0,f=a.length;c<d;)a[f++]=b[c++];if(d!==d)for(;b[c]!==m;)a[f++]=b[c++];a.length=f;return a},getClosestNode:function(a,b,d,e){do a=a[b];while(a&&(d&&!c.matches(d,a)||!c.isElement(a)));c.isDefined(e)&&null!==a&&c.nodeType(e,a);return a},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},camelCase:function(a){n[a]||(n[a]=a.replace(/^-ms-/,"ms-").replace(/^.|-./g,
function(a,d){return 0===d?a.toLowerCase():a.substr(1).toUpperCase()}));return n[a]},map:function(a,b){var d,e=[],f,g;if(c.likeArray(a))for(f=0,g=a.length;f<g;f++)d=b(a[f],f),null!==d&&e.push(d);else for(f in a)d=b(a[f],f),null!==d&&e.push(d);return e},isXML:function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1}});var $="nodeType",V={idClassTagNameExp:/^(?:#([\w-]+)|\.([\w-]+)|(\w+))$/,tagNameAndOrIdAndOrClassExp:/^(\w+)(?:#([\w-]+)|)(?:\.([\w-]+)|)$/,pseudos:/(.*):(\w+)(?:\(([^)]+)\))?$\s*/};
c.extend({pseudos:{disabled:function(){return!0===this.disabled},enabled:function(){return!1===this.disabled&&"hidden"!==this.type},selected:function(){this.parentNode&&this.parentNode.selectedIndex;return!0===this.selected},checked:function(){var a=this.nodeName.toLowerCase();return"input"===a&&!!this.checked||"option"===a&&!!this.selected},parent:function(){return this.parentNode},first:function(a){if(0===a)return this},last:function(a,b){if(a===b.length-1)return this},empty:function(){var a;for(a=
this.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},eq:function(a,b,d){if(a===d)return this},contains:function(a,b,d){if(-1<c(this).text().indexOf(d))return this},has:function(a,b,d){if(c.select(this,d).length)return this},radio:function(){return"radio"===this.type},checkbox:function(){return"checkbox"===this.type},file:function(){return"file"===this.type},password:function(){return"password"===this.type},submit:function(){return"submit"===this.type},image:function(){return"image"===
this.type},button:function(){var a=this.nodeName.toLowerCase();return"input"===a&&"button"===this.type||"button"===a},target:function(){var a=s.location&&s.location.hash;return a&&a.slice(1)===this.id},input:function(){return/input|select|textarea|button/i.test(this.nodeName)}},select:function(a,b){var d,e=[];b=ya(b);if(d=V.idClassTagNameExp.exec(a))if(a=d[1])e=(e=b.getElementById(a))?[e]:[];else if(a=d[2])e=b.getElementsByClassName(a);else{if(a=d[3])e=b.getElementsByTagName(a)}else if(d=V.tagNameAndOrIdAndOrClassExp.exec(a)){var f=
b.getElementsByTagName(d[1]),g=d[2],k=d[3];c.each(f,function(){var a;(a=this.id===g)||(a=c.support.classList?this.classList.contains(k):c.contains((""+this.className).split(" "),k));a&&e.push(this)})}else if(d=V.pseudos.exec(a)){var h=c.pseudos[d[2]],l=d[3];try{a=b.querySelectorAll(d[1])}catch(Q){console.error("error performing selector: %o",a)}e=c.unique(c.map(a,function(b,d){try{return h.call(b,d,a,l)}catch(c){console.error("error performing selector: %o",a)}}))}else try{e=b.querySelectorAll(a)}catch(m){console.error("error performing selector: %o",
a)}return c.isNodeList(e)?p.call(e):c.isElement(e)?[e]:e}});var y=[],L=!1,ra=!1;c.extend({ready:function(a,b){b=b||document;L?setTimeout(function(){a(b)},1):(y.push({fn:a,ctx:b}),"complete"===document.readyState?setTimeout(K,1):ra||(document.addEventListener("DOMContentLoaded",K,!1),s.addEventListener("load",K,!1),ra=!0))}});var t={};c.extend({hasData:function(a,b){if(a instanceof c){if(aa(a[0],b))return!0}else if(aa(c(a)[0],b))return!0;return!1},removeData:function(a,b){if(a instanceof c){if(M(a[0],
b))return!0}else if(M(c(a)[0],b))return!0;return!1},data:function(a,b,d){len=arguments.length;keyType=typeof b;if(1===len){var e=c.getUID(a[0]);(t[e]||(t[e]={}))[b]=d}else 2===len&&z(a[0],b)},getAllData:function(a){return z(a[0])}});c.fn.extend({removeData:function(a){return this.each(function(){M(this,a)})},data:function(a,b){len=arguments.length;keyType=typeof a;return 1===len?1===this.elems.length?z(this.elems[0],a):this.elems.map(function(b){return z(b,a)}):2===len?this.each(function(){var d=
c.getUID(this);(t[d]||(t[d]={}))[a]=b}):z(this[0])}});var W=/[^\.]*(?=\..*)\.|.*/,H=/\..*/,na="hasOwnProperty",sa=q.documentElement||{},x={},Aa=/^key/,za=/^(?:mouse|pointer|contextmenu)|click/,da={},r=Array.prototype,F=Object.prototype,p=r.slice,pa=r.concat,qa=F.toString,I={disabeled:function(a,b){if(a.disabeled&&"click"===b)return!0},nodeType:function(a){if(c.nodeType(3,a)||c.nodeType(8,a))return!0}},X={pointerenter:{fix:"pointerover",condition:ca},pointerleave:{fix:"pointerout",condition:ca},mouseenter:{fix:"mouseover",
condition:ba},mouseleave:{fix:"mouseout",condition:ba},mousewheel:{fix:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},N="altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" ");u.prototype={preventDefault:function(){this.originalEvent.preventDefault?this.originalEvent.preventDefault():this.originalEvent.returnValue=!1},stopPropagation:function(){this.originalEvent.stopPropagation?this.originalEvent.stopPropagation():
this.originalEvent.cancelBubble=!0},stop:function(){this.preventDefault();this.stopPropagation();this.stopped=!0},stopImmediatePropagation:function(){this.originalEvent.stopImmediatePropagation&&this.originalEvent.stopImmediatePropagation();this.isImmediatePropagationStopped=function(){return!0}},isImmediatePropagationStopped:function(){return this.originalEvent.isImmediatePropagationStopped&&this.originalEvent.isImmediatePropagationStopped()},clone:function(a){var b=u(this,this.element);b.currentTarget=
a;return b}};c.Events={add:function(a,b,d,e,f){var g,k,h,l,Q,n;if(I.disabeled(a,b)||I.nodeType(a))return!1;if(d===m&&"object"===typeof b)for(g in b)b.hasOwnProperty(g)&&c.Events.add.call(this,a,g,b[g]);else{c.isFunction(d)?(l=p.call(arguments,3),e=g=d):(g=e,l=p.call(arguments,4),e=c.Events.delegate(d,g));k=b.split(" ");1===f&&(e=c.Events.once(c.Events.remove,a,b,e,g));for(h=k.length;h--;)(n=c.Events.putHandler(Q=c.Kernel(a,k[h].replace(H,""),e,g,k[h].replace(W,"").split("."),l,!1)))&&a.addEventListener(Q.eventType,
c.Events.rootListener,!1);return a}},remove:function(a,b,d){var e=c.isString(b),f;if(e&&0<b.indexOf(" ")){b=b.split(b);for(f=b.length;f--;)c.Events.remove(a,b[f],d);return a}(f=e&&b.replace(H,""))&&X[f]&&(f=X[f].fix);if(!b||e){if(b=e&&b.replace(W,""))b=b.split(".");c.Events.removeListener(a,f,d,b)}else if(c.isFunction(b))c.Events.removeListener(a,null,b);else for(var g in b)b.hasOwnProperty(g)&&c.Events.remove(a,g,b[g]);return a},delegate:function(a,b){function d(b,d){for(var e,h=c.isString(a)?c.select(a,
d):a;b&&b!==d;b=b.parentNode)if(null!==h)for(e=h.length;e--;)if(h[e]===b)return b}function e(a){if(!0!==a.target.disabled){var c=d(a.target,this);c&&b.apply(c,arguments)}}e.__handlers={ft:d,selector:a};return e},removeListener:function(a,b,d,e){b=b&&b.replace(H,"");b=c.Events.getHandler(a,b,null,!1);var f={},g,k;g=0;for(k=b.length;g<k;g++)d&&b[g].original!==d||!b[g].inNamespaces(e)||(c.Events.delHandler(b[g]),f[b[g].eventType]||(f[b[g].eventType]={t:b[g].eventType,c:b[g].type}));for(g in f)c.Events.hasHandler(a,
f[g].t,null,!1)||a.removeEventListener(f[g].t,c.Events.rootListener,!1)},once:function(a,b,d,c,f){return function(){c.apply(this,arguments);a(b,d,f)}},rootListener:function(a,b){var d=c.Events.getHandler(this,b||a.type,null,!1),e=d.length,f=0;a=u(a,this,!0);b&&(a.type=b);for(;f<e&&!a.isImmediatePropagationStopped();f++)d[f].removed||d[f].handler.call(this,a)},wrappedHandler:function(a,b,d,c){function f(d,f){return b.apply(a,c?p.call(f).concat(c):f)}var g=d?function(c){var e=b.__handlers?b.__handlers.ft(c.target,
a):this;if(d.apply(e,arguments))return c&&(c.currentTarget=e),f(c,arguments)}:function(d){b.__handlers&&(d=d.clone(b.__handlers?b.__handlers.ft(d.target,a):void 0));return f(d,arguments)};g.__handlers=b.__handlers;return g},findIt:function(a,b,d,e,f,g){if(b&&"*"!==b){var k=0,h=x[f?"r":"#"+b];if(h)for(f=h.length;k<f&&("*"!==a&&!h[k].matches(a,d,e)||g(h[k],h,k,b));k++);}else for(k in x)(k.charAt(0)===f||1)&&c.Events.findIt(a,k.substr(1),d,e,f,g)},hasHandler:function(a,b,d,c){if(c=x[(c?"r":"#")+b])for(b=
c.length;b--;)if(!c[b].root&&c[b].matches(a,d,null))return!0;return!1},getHandler:function(a,b,d,e){var f=[];c.Events.findIt(a,b,d,null,e,function(a){f.push(a)});return f},putHandler:function(a){var b=!a.root&&!this.hasHandler(a.element,a.type,null,!1),d=(a.root?"r":"#")+a.type;(x[d]||(x[d]=[])).push(a);return b},delHandler:function(a){c.Events.findIt(a.element,a.type,null,a.handler,a.root,function(a,d,c){d.splice(c,1);a.removed=!0;0===d.length&&delete x[(a.root?"r":"#")+a.type];return!1})}};c.extend({eventHooks:{keys:function(a,
b){b.keyCode=a.keyCode||a.which;return N.concat(["char","charCode","key","keyCode"])},mouse:function(a,b){b.rightClick=3===a.which||2===a.button;b.pos={x:0,y:0};if(a.pageX||a.pageY)b.clientX=a.pageX,b.clientY=a.pageY;else if(a.clientX||a.clientY)b.clientX=a.clientX+q.body.scrollLeft+sa.scrollLeft,b.clientY=a.clientY+q.body.scrollTop+sa.scrollTop;return N.concat("button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "))}},Kernel:function(a,b,d,e,f,g){if(!(this instanceof
c.Kernel))return new c.Kernel(a,b,d,e,f,g);var k=X[b];"unload"===b&&(d=c.Events.once(c.Events.removeListener,a,b,d,e));k&&(k.condition&&(d=c.Events.wrappedHandler(a,d,k.condition,g)),b=k.fix||b);this.element=a;this.type=b;this.original=e;this.namespaces=f;this.eventType=b;this.target=a;this.handler=c.Events.wrappedHandler(a,d,null,g)}});c.Kernel.prototype.inNamespaces=function(a){var b,d,c=0;if(!a)return!0;if(!this.namespaces)return!1;for(b=a.length;b--;)for(d=this.namespaces.length;d--;)a[b]==this.namespaces[d]&&
c++;return a.length===c};c.Kernel.prototype.matches=function(a,b,d){return this.element===a&&(!b||this.original===b)&&(!d||this.handler===d)};c.fn.extend({on:function(a,b,d,e){return this.each(function(){c.Events.add(this,a,b,d,e)})},one:function(a,b,d){return this.on(a,b,d,1)},off:function(a,b){return this.each(function(){c.Events.remove(this,a,b)})},trigger:function(a,b){var d=this[0],e=a.split(" "),f,g,k,h,l,m;if(I.disabeled(d,a)||I.nodeType(d))return!1;for(f=e.length;f--;){a=e[f].replace(H,"");
if(l=e[f].replace(W,""))l=l.split(".");if(l||b)for(alert("dd"),m=c.Events.getHandler(d,a,null,!1),g=u(null,d),g.type=a,h=b?"apply":"call",b=b?[g].concat(b):g,g=0,k=m.length;g<k;g++){if(m[g].inNamespaces(l))m[g].handler[h](d,b)}else h=q.createEvent("HTMLEvents"),h.initEvent(a,!0,!0,win,1),d.dispatchEvent(h)}return d}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,a,c):this.trigger(b)}});c.fn.extend({empty:function(){return this.removeData().each(function(){this.textContent=""})},remove:function(){return this.removeData().each(function(){var a=c(this).find("*"),a=a.add(this);c.each(a,function(){c.event.remove(this)});this.parentNode&&this.parentNode.removeChild(this)})},clone:function(){return this.map(function(){return this.cloneNode(!0)})}});var J={tabindex:"tabIndex",readonly:"readOnly",
"for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},Na={multiple:!0,selected:!0,checked:!0,disabled:!0,readOnly:!0,required:!0,open:!0},Oa={input:!0,select:!0,option:!0,textarea:!0,button:!0,form:!0,details:!0},ta={first:"beforeBegin",middle:"afterBegin",center:"afterBegin",last:"beforeEnd"};c.extend({getValue:function(a){if("SELECT"===
a.nodeName&&a.multiple){for(var b,d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:d.length,k=0>e?g:a?e:0;k<g;k++)if(b=d[k],!(!b.selected&&k!==e||b.disabled||b.parentNode.disabled&&c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}return f}return a.value},getText:function(a){var b,d="",e=0;if(!a.nodeType)for(;b=a[e++];)d+=c.getText(b);else if(ea(a)){if(c.isString(a.textContent))return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)d+=c.getText(a)}else if(c.nodeType(3,
a)||c.nodeType(4,a))return a.nodeValue;return d},prop:function(a,b,d){if(!(c.nodeType(2,a)||c.nodeType(3,a)||c.nodeType(8,a)))return b=J[b]||b,d!==m?a[b]=d:a[b]},attr:function(a,b,d){if(!(c.nodeType(2,a)||c.nodeType(3,a)||c.nodeType(8,a))){if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);if(c.isUndefined(d)){if("value"===b&&"input"===b.nodeName.toLowerCase())return c.getValue(a);a=a.getAttribute(b);return null===a?m:a}return a.setAttribute(b,d+"")}}});c.fn.extend({text:function(a,b){return c.isUndefined(a)?
c.getText(this):this.empty().each(function(){ea(this)&&(c.isDefined(HTMLElement)&&HTMLElement.prototype.insertAdjacentText?this.insertAdjacentText(ta[b]?ta[b]:"beforeEnd",a):this.textContent=a)})},html:function(a,b){return a===m&&1===this[0].nodeType?this[0].innerHTML:c.isString(a)?this.removeData().each(function(){c.nodeType(1,this)&&(this.textContent="",this.insertAdjacentHTML("beforeend",a||""))}):this.empty().append(a)},val:function(a){return a?this.each(function(b,d){var e;c.nodeType(1,d)&&(e=
c.isFunction(a)?a.call(d,b,c(d).val()):a,null===e?e="":"number"===typeof e&&(e+=""),d.value=e)}):this[0]&&c.getValue(this[0])},attr:function(a,b){return c.isObject(a)?this.each(function(b,e){c.each(a,function(a,b){c.attr(e,a,b)})}):c.isUndefined(b)?c.attr(this[0],a):1===this.length?c.attr(this[0],a,b):this.each(function(){return c.attr(this,a,b)})},removeAttr:function(a){var b,d,e,f,g=a&&a.match(/\S+/g);return this.each(function(){b=this;f=0;if(g&&c.nodeType(1,b))for(;d=g[f++];){e=J[d]||d;var a=b,
h=Na[d.toLowerCase()];h&&Oa[a.nodeName]&&h&&(b[e]=!1);b.removeAttribute(d)}})},prop:function(a,b){return c.isObject(a)?this.each(function(b,e){c.each(a,function(a,b){c.prop(e,a,b)})}):c.isUndefined(b)?this[0]&&this[0][J[a]||a]:c.prop(element,key,b)},removeProp:function(a){return this.each(function(){delete this[J[a]||a]})},append:function(a){return this.each(function(){if(c.isString(a))this.insertAdjacentHTML("beforeend",a);else{if(a instanceof c){if(1===a.length)return alert(a[0]),this.appendChild(a[0]);
var b=this;return c.each(a,function(){b.appendChild(this)})}try{this.appendChild(a)}catch(d){console.error("What you try to do, can't be done! Sorry!!","")}}})},appendTo:function(a){return this.each(function(){c(a).append(this)})},prepend:function(a){var b;return this.each(function(){if(c.isString(a))this.insertAdjacentHTML("afterbegin",a);else if(b=this.childNodes[0])this.insertBefore(a,b);else{if(a instanceof c){if(1===a.length)return this.appendChild(a[0]);var d=this;return c.each(a,function(){d.appendChild(this)})}try{this.appendChild(a)}catch(e){console.error("What you try to do, can't be done! Sorry!!",
"")}}})},prependTo:function(a){return this.each(function(){c(a).prepend(this)})},after:function(a){var b;return this.each(function(){c.isString(a)?this.insertAdjacentHTML("afterend",a):(b=c.getClosestNode(this,"nextSibling"))?a instanceof c?this.parentNode&&this.parentNode.insertBefore(a[0],b):this.parentNode&&this.parentNode.insertBefore(a,b):a instanceof c?this.parentNode&&this.parentNode.appendChild(a[0]):this.parentNode&&this.parentNode.appendChild(a)})},before:function(a){return this.each(function(){c.isString(a)?
this.insertAdjacentHTML("beforebegin",a):a instanceof c?this.parentNode&&this.parentNode.insertBefore(a[0],this):this.parentNode&&this.parentNode.insertBefore(a,this)})},replaceWith:function(a){return"string"===typeof a?this.before(a).remove():this.each(function(b,d){c.each(a,function(){d.parentNode.insertBefore(this,d)})})}});c.fn.extend({pluckNode:function(a){return this.map(function(b){return c.getClosestNode(b,a)})},closest:function(a){return this.map(function(b){return c.nodeType(1,b)&&c.matches(b,
a)?b:c.getClosestNode(b,"parentNode",a,11)})},index:function(a){return a?this.indexOf(c(a)[0]):this.parent().children().indexOf(this[0])||-1},add:function(a,b){var d=a;c.isString(a)&&(d=c(a,b).elems);return this.concat(d)},parent:function(a){return c(this.pluck("parentNode"),a,11)},parents:function(a){for(var b=[],d=this.elems,e=function(a){if((a=a.parentNode)&&a!==document&&0>b.indexOf(a))return b.push(a),a};0<d.length&&d[0]!==m;)d=d.map(e);return c.create(b,a)},children:function(a){return c.create(this.reduce(function(a,
d){var c=p.call(d.children);return a.concat(c)},[]),a)},next:function(a){return a?c(this.pluckNode("nextSibling").filter(a)):c(this.pluckNode("nextSibling"))},prev:function(a){return a?c(this.pluckNode("previousSibling").filter(a)):c(this.pluckNode("previousSibling"))},first:function(){return c(this.get(0))},last:function(){return c(this.get(-1))},contents:function(){return this.map(function(a){return a.contentDocument||p.call(a.childNodes)})},siblings:function(a){var b=[],d,e,f,g;n[a]||(this.each(function(){e=
this;d=p.call(e.parentNode.childNodes);f=0;for(g=d.length;f<g;f++)c.isElement(d[f])&&d[f]!==e&&b.push(d[f])}),n[a]=b);return c.create(n[a],a)}});c.extend({parseJSON:function(a){return JSON.parse(a+"")},parseXML:function(a){var b,d;if(!a||"string"!==typeof a)return null;try{d=new DOMParser,b=d.parseFromString(a,"text/xml")}catch(c){b=m}return!b||b.getElementsByTagName("parsererror").length?Error("Invalid XML: "+a):b}});var ua={letterSpacing:"0",fontWeight:"400"},n=[],ma=["Webkit","O","Moz","ms"],A=
["Top","Right","Bottom","Left"],Pa={position:"absolute",visibility:"hidden",display:"block"},Ba=/^margin/,ha=/^([+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|))(?!px)[a-z%]+$/i,Qa=/^(none|table(?!-c[ea]).+)/,Ra=RegExp("^("+/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source+")(.*)$","i"),Sa=/^([+-])=([+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|))(.*)/i;c.extend({cssProps:{"float":"cssFloat"},cssNumber:{columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,
zIndex:!0,zoom:!0},cssHooks:{opacity:{get:function(a,b){if(b){var d=O(a,"opacity");return""===d?"1":d}}}},pixelsToUnity:function(a,b,d,e){if(""===b||"px"===b)return a;if("em"===b)return a/c.css(d,"fontSize","");if("%"===b){/^(left$|right$|margin|padding)/.test(e)?e="width":/^(top|bottom)$/.test(e)&&(e="height");if(d=/^(relative|absolute|fixed)$/.test(c.css(d,"position"))?d.offsetParent:d.parentNode)if(e=c.css(d,e,!0),0!==e)return a/e*100;return 0}c.pixelsToUnity.units===m&&(d=c.pixelsToUnity.units=
{},e=document.createElement("div"),e.style.width="100cm",document.body.appendChild(e),d.mm=e.offsetWidth/1E3,document.body.removeChild(e),d.cm=10*d.mm,d.inn=2.54*d.cm,d.pt=1*d.inn/72,d.pc=12*d.pt);return(b=c.pixelsToUnity.units[b])?a/b:a},css:function(a,b,d,e){var f,g;g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=la(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));f===m&&(f=O(a,b,e));"normal"===f&&b in ua&&(f=ua[b]);return""===d||d?(a=parseFloat(f),!0===d||c.isNumeric(a)?
a||0:f):f},style:function(a,b,d,e){if(a&&!c.nodeType(3,a)&&!c.nodeType(8,a)&&a.style){var f,g,k,h=c.camelCase(b),l=a.style;b=c.cssProps[h]||(c.cssProps[h]=la(a.style,h));k=c.cssHooks[b]||c.cssHooks[h];if(d!==m)g=typeof d,"string"===g&&(f=Sa.exec(d))&&(d=c.css(a,b,"","",b,k),d=c.pixelsToUnity(d,f[3],a,b)+(f[1]+1)*f[2],g="number"),null!==d&&d===d&&("number"!==g||c.cssNumber[h]||(d+=f&&f[3]?f[3]:"px"),""===d&&/background/i.test(b)&&(l[b]="inherit"),k&&"set"in k&&(d=k.set(a,d,e))===m||(l[b]=d));else return l[b]}}});
c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return 0===a.offsetWidth&&Qa.test(c.css(a,"display"))?c.swap(a,Pa,function(){return ga(a,b,f)}):ga(a,b,f)},set:function(a,e,f){var g=f&&a.ownerDocument.defaultView.getComputedStyle(a,null);a=f?ia(a,b,f,"border-box"===c.css(a,"boxSizing",!1,g),g):0;return(f=Ra.exec(e))?Math.max(0,f[1]-(a||0))+(f[2]||"px"):e}}});c.fn.extend({show:function(){return this.each(function(){ja(this)})},hide:function(){return this.each(function(){ka(this)})},
toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){P(this)?ja(this):ka(this)})},css:function(a,b){if(c.isDefined(b))return 1===this.length?c.style(this[0],a,b):this.each(function(){c.style(this,a,b)});if(c.isUndefined(b))return c.isString(a)?this[0]&&c.css(this[0],a):this.each(function(){var b=this;c.each(a,function(a,f){c.style(b,a,f)})})},setOpacity:function(a){if(c.isNumber)return this.each(function(){this.style.opacity=a/100})},height:function(a){return c.isDefined(a)?
this.each(function(){c.style(this,"height",a)}):v(this[0],"height","content")},outerHeight:function(a){return v(this[0],"height","boolean"===typeof a?"margin":"border")},innerHeight:function(){return v(this[0],"height","padding")},width:function(a){return c.isDefined(a)?this.each(function(){c.style(this,"width",a)}):v(this[0],"width","content")},outerWidth:function(a,b){return v(this[0],"width","boolean"===typeof a?"margin":"border",!0===typeof b?"margin":"border")},innerWidth:function(){return v(this[0],
"width","padding")},scrollTop:function(a){var b=this[0],c=fa(b);if(a===m)return a?a.pageYOffset:b.scrollTop;c?c.scrollTo(s.pageYOffset):b.scrollTop=a},scrollLeft:function(a){var b=this[0],c=fa(b);if(a===m)return a?a.pageXOffset:b.scrollLeft;c?c.scrollTo(s.pageXOffset):b.scrollLeft=a}});var Fa="createElement",na="hasOwnProperty",T=q.head||q.getElementsByTagName("head")[0],oa=0,D,Ga=-1!==c.indexOf(navigator.userAgent,"MSIE 10.0"),oa=0,S=Date.now||function(){return(new Date).getTime()},va={"*":"*/".concat("*"),
text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript",js:"application/javascript, text/javascript"};c.extend({ajax:function(a,b){a=a||{};b=b||function(){};var d,e=a.headers||{},f=nativeKeys(e),g=-1,k=f.length,h=(a.method||"GET").toLowerCase(),l=c.isString(a)?a:a.url,n=a.type?a.type.toLowerCase():"",q=null,p=!1!==(a.processData||!0)&&a.data&&!c.isString(a.data)?Ca(a.data):a.data||null,s=!1;if(!l)return!1;"jsonp"!==n&&"get"!==h.toLowerCase()||!p||
(l=(l+"&"+p).replace(/[&?]+/,"?"),p=null);if("jsonp"===n&&/(=)\?(?=&|$)|\?\?/.test(l))return Ea(a,b,l);if(!0===a.crossOrigin){var r=win.XMLHttpRequest?new XMLHttpRequest:null;if(r&&"withCredentials"in r)d=r;else if(win.xDomainRequest)d=new "XDomainRequest";else throw"Browser does not support cross-origin requests";}d.open(h,l,!1===a.async?!1:!0);e.Accept=e.Accept||va[n]||va["*"];a.crossOrigin||e.requestedWith||(e.requestedWith="XMLHttpRequest");for((a.contentType||a.data&&"get"!==n.toLowerCase())&&
d.setRequestHeader("Content-Type",a.contentType||"application/x-www-form-urlencoded");++g<k;)d.setRequestHeader(c.trim(f[g]),e[f[g]]);c.isDefined(a.withCredentials)&&c.isDefined(d.withCredentials)&&(d.withCredentials=!!a.withCredentials);0<a.timeout&&(q=setTimeout(function(){d.abort()},a.timeout));win.XDomainRequest&&d instanceof win.xDomainRequest?(d.onload=b,d.onerror=err,d.onprogress=function(){},s=!0):d.onreadystatechange=function(){if(4===d.readyState)if(200<=d.status&&300>d.status||304===d.status){var b;
d&&("json"===n&&null===(b=JSON.parse(d.responseText))&&(b=d.responseText),b="xml"===n?d.responseXML&&d.responseXML.parseError&&d.responseXML.parseError.errorCode&&d.responseXML.parseError.reason?null:d.responseXML:b||d.responseText);!b&&p&&(b=p);a.success&&a.success(b)}else a.error!==m&&(null!==q&&clearTimeout(q),a.error("error",a,d))};a.before&&a.before(d);s?setTimeout(function(){d.send(p)},200):d.send(p);return d},getJSON:function(a,b,d,e){c.ajax({url:a,method:"JSON",contentType:"application/json",
error:c.isFunction(e)?e:function(a){},data:c.isObject(b)?b:{},success:c.isFunction?d:function(a){}})},get:function(a,b,d,e){c.ajax({url:a,method:"GET",contentType:"",error:c.isFunction(e)?e:function(a){},data:c.isObject(b)?b:{},success:c.isFunction?d:function(a){}})},post:function(a,b,d,e){c.ajax({url:a,method:"POST",contentType:"",error:c.isFunction(e)?e:function(a){},data:c.isObject(b)?b:{},success:c.isFunction?d:function(a){}})}});var C=!!document.createElement("p").classList,Y=/\S+/g,Z=/[\t\r\n\f]/g;
c.fn.extend({addClass:function(a){if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});var b,d,e,f,g=(a||"").match(Y)||[];return this.each(function(a,h){if(C&&c.nodeType(1,h))return c.each(g,function(a,b){return h.classList.add(b)});if(b=c.nodeType(1,h)&&(h.className?(" "+h.className+" ").replace(Z," "):" ")){for(d=0;e=g[d++];)0>b.indexOf(" "+e+" ")&&(b+=e+" ");f=c.trim(b);h.className!==f&&(h.className=f)}})},removeClass:function(a){var b,d,e,f,g;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,
b,this.className))});b=(a||"").match(Y)||[];return this.each(function(k,h){if(!a)return h.className="";if(C&&c.nodeType(1,h))return c.each(b,function(a,b){h.classList.remove(b)});if(d=c.nodeType(1,h)&&(h.className?(" "+h.className+" ").replace(Z," "):"")){for(f=0;e=b[f++];)for(;0<=d.indexOf(" "+e+" ");)d=d.replace(" "+e+" "," ");g=a?c.trim(d):"";h.className!==g&&(h.className=g)}})},hasClass:function(a){for(var b=" "+a+" ",d=0,e=this.length;d<e;d++){if(C&&c.nodeType(1,this[d]))return this[d].classList.contains(a);
if(c.nodeType(1,this[d])&&0<=(" "+this[d].className+" ").replace(Z," ").indexOf(b))return!0}return!1},replaceClass:function(a,b){var d,e;return this.each(function(){d=this.className.split(" ");e=!1;for(var f=d.length;f--;)d[f]==a&&(e=!0,d[f]=b);if(!e)return c(this).addClass(b,this);this.className=d.join(" ")})},tempClass:function(a,b){return this.each(function(d,e){c(e).addClass(a);setTimeout(function(){c(e).removeClass(a)},b||60)})},allClass:function(){return C?this[0].classList:this},toggleClass:function(a,
b){var d=typeof a;return"boolean"===typeof b&&"string"===d?b?this.addClass(a):this.removeClass(a):c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,this.className,b),b)}):this.each(function(){C&&this.classList.toggle(a);if("string"===d)for(var b,f=0,g=c(this),k=a.match(Y)||[];b=k[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else if(d===typeof m||"boolean"===d)this.className&&c.data(this,"__className__",this.className),this.className=this.className||!1===a?"":c.data(this,
"__className__")||""})}});var Ta=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Ua=/^\s*<(\w+|!)[^>]*>/,Va=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,r=document.createElement("table"),wa=document.createElement("tr"),xa={tr:document.createElement("tbody"),tbody:r,thead:r,tfoot:r,td:wa,th:wa,"*":document.createElement("div")},Wa="val css html text data width height offset".split(" ");c.extend({fragment:function(a,b,d){var e,f,g;Ta.test(a)&&(e=c(document.createElement(RegExp.$1)));e||(a.replace&&
(a=a.replace(Va,"<$1></$2>")),b===m&&(b=Ua.test(a)&&RegExp.$1),b in xa||(b="*"),g=xa[b],g.innerHTML=""+a,e=c.each(p.call(g.childNodes),function(){g.removeChild(this)}));c.isPlainObject(d)&&(f=c(e),c.each(d,function(a,b){if(-1<Wa.indexOf(a))f[a](b);else f.attr(a,b)}));return e}});c.fn.extend({wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b(a)?a.call(this,d):a)})},wrapAll:function(a){if(this[0]){c(this[0]).before(a=c(a,this[0].ownerDocument).eq(0).clone(!0));for(var b;(b=
a.children()).length;)a=b.first();c(a).append(this)}return this},unwrap:function(){this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(c(this).children()).remove()});return this}});(function(){var a=document.createDocumentFragment().appendChild(document.createElement("div")),b=document.createElement("input");a.appendChild(b);G.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";G.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();
var Ia=/^(?:checkbox|radio)$/i;c.fn.extend({clone:function(){var a,b,d,e;return this.map(function(f){var g=c.Events.getHandler(f,"",null,!1),k=g.length,h=0,l,m;b=c(f).data();for(a=f.cloneNode(!0);h<k;h++)g[h].original&&(l=[a,g[h].type],(m=g[h].handler.__handler)&&l.push(m.selector),l.push(g[h].original),c.Events.add.apply(null,l));c.each(b,function(b,d){c.data(a,b,d)});if(!c.support.noCloneChecked&&(c.nodeType(1,f)||c.nodeType(11,f))&&!c.isXML(f))for(e=E(a),d=E(f),h=0,k=d.length;h<k;h++)Ha(d[h],e[h]);
e=E(a,"script");0<e.length&&Ja(e,!c.contains(f.ownerDocument,f)&&E(f,"script"));return a})}});s.hAzzle=c}})(window);